require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');
const OpenAI = require('openai');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// ---------------------------------------------------------------------
// STARTUP CHECK: Ensure API Key exists
// ---------------------------------------------------------------------
const activeApiKey = process.env.NEMOTRON_API_KEY || process.env.OPENROUTER_API_KEY;

if (!activeApiKey) {
    console.error("=====================================================");
    console.error("🚨 CRITICAL WARNING: Missing API Key!");
    console.error("Please set OPENROUTER_API_KEY or NEMOTRON_API_KEY in your .env");
    console.error("=====================================================");
}

const ai = new OpenAI({
    baseURL: process.env.NEMOTRON_BASE_URL || 'https://openrouter.ai/api/v1',
    apiKey: activeApiKey || 'missing-key', 
});

// ---------------------------------------------------------------------
// MASSIVE QUESTION DATABASE (150 Questions Total - 25 Per Category)
// ---------------------------------------------------------------------
const questionsDB = {
    "TechAI": [
        {"text":"When your computer freezes, what is your first reaction?","options":[{"text":"Troubleshoot and fix it myself.","tags":{"Technical":3,"ProblemSolving":2}},{"text":"Search Google/YouTube for a fix.","tags":{"Analytical":2,"Resourceful":3}},{"text":"Ask a friend who is good with tech.","tags":{"Communication":2}},{"text":"Restart it and hope for the best.","tags":{"Easygoing":1}}]},
        {"text":"What excites you most about AI?","options":[{"text":"How it processes massive data.","tags":{"Analytical":3}},{"text":"How it can generate art/music.","tags":{"Creative":3}},{"text":"How it can help people in daily life.","tags":{"Empathy":3}},{"text":"How it automates boring tasks.","tags":{"Logical":3}}]},
        {"text":"How do you handle a messy folder of files?","options":[{"text":"Write a script to organize them.","tags":{"Technical":3,"ProblemSolving":3}},{"text":"Manually sort into perfect folders.","tags":{"Organized":3}},{"text":"Only search for what I need.","tags":{"Practical":2}},{"text":"Leave it messy, I know where things are.","tags":{"Adaptable":2}}]},
        {"text":"If you could invent one thing, it would be:","options":[{"text":"A new coding language.","tags":{"Technical":3,"Analytical":2}},{"text":"A robot that cleans the house.","tags":{"Practical":3}},{"text":"A new musical instrument.","tags":{"Creative":3}},{"text":"An app to connect lonely people.","tags":{"Empathy":3}}]},
        {"text":"What is your approach to password security?","options":[{"text":"Use a password manager with complex hashes.","tags":{"Technical":3,"Organized":2}},{"text":"Use a memorable phrase with numbers.","tags":{"Practical":3}},{"text":"Use the same password for everything.","tags":{"Easygoing":1}},{"text":"Write them down in a physical notebook.","tags":{"Organized":2}}]},
        {"text":"When learning a complex idea, you:","options":[{"text":"Ask about the specific mechanics.","tags":{"Analytical":3}},{"text":"Imagine it visually.","tags":{"Creative":2}},{"text":"Relate it to people.","tags":{"Empathy":3}},{"text":"Write bullet points.","tags":{"Organized":3}}]},
        {"text":"What type of puzzles do you enjoy most?","options":[{"text":"Logic/math puzzles (Sudoku).","tags":{"Analytical":3,"ProblemSolving":2}},{"text":"Word puzzles (Crosswords).","tags":{"Communication":2}},{"text":"Visual puzzles (Jigsaw).","tags":{"Creative":2}},{"text":"Real-world challenges.","tags":{"Practical":3}}]},
        {"text":"If you ran a tech company, you would be the:","options":[{"text":"Lead Developer writing the best code.","tags":{"Technical":3}},{"text":"CEO pitching the vision to investors.","tags":{"Leadership":3}},{"text":"Lead Designer making the UI beautiful.","tags":{"Creative":3}},{"text":"Project Manager keeping everyone on track.","tags":{"Organized":3}}]},
        {"text":"What do you notice first about a new app?","options":[{"text":"How fast and smooth it runs.","tags":{"Technical":3}},{"text":"How cool the layout looks.","tags":{"Creative":3}},{"text":"How easy it is to understand.","tags":{"Empathy":2}},{"text":"The privacy settings.","tags":{"Analytical":3}}]},
        {"text":"Which part of building a website sounds most fun?","options":[{"text":"Writing the backend code.","tags":{"Technical":3,"Analytical":2}},{"text":"Designing the logo and colors.","tags":{"Creative":3}},{"text":"Writing the text and articles.","tags":{"Communication":3}},{"text":"Planning how pages link together.","tags":{"Organized":3}}]},
        {"text":"How do you prefer to learn something new?","options":[{"text":"Taking it apart to see how it works.","tags":{"Analytical":3,"Technical":2}},{"text":"Watching a visual tutorial.","tags":{"Creative":2}},{"text":"Reading the official manual.","tags":{"Organized":2}},{"text":"Practicing with a group.","tags":{"Communication":3}}]},
        {"text":"Your perfect work environment is:","options":[{"text":"Quiet room with dual monitors.","tags":{"Technical":3,"Independent":2}},{"text":"Lively office sharing ideas.","tags":{"Communication":3,"Creative":1}},{"text":"A highly organized desk.","tags":{"Organized":3}},{"text":"Flexible space to move around.","tags":{"Adaptable":3}}]},
        {"text":"If you had to read a book right now, it would be:","options":[{"text":"Sci-fi or future technology.","tags":{"Imaginative":3,"Technical":2}},{"text":"A biography of a leader.","tags":{"Leadership":3}},{"text":"A mystery novel.","tags":{"Analytical":3}},{"text":"A how-to guide.","tags":{"Practical":3}}]},
        {"text":"You find a bug in a video game. You:","options":[{"text":"Try to replicate it to see why it happens.","tags":{"Analytical":3,"ProblemSolving":2}},{"text":"Use it to your advantage to win.","tags":{"Logical":3}},{"text":"Report it to the developers.","tags":{"Organized":2}},{"text":"Ignore it and keep playing.","tags":{"Easygoing":2}}]},
        {"text":"What is your favorite subject in school?","options":[{"text":"Computer Science / IT.","tags":{"Technical":3}},{"text":"Math / Physics.","tags":{"Analytical":3}},{"text":"Art / Graphic Design.","tags":{"Creative":3}},{"text":"History / English.","tags":{"Communication":2}}]},
        {"text":"When buying a laptop, you look for:","options":[{"text":"RAM, Processor speed, and OS.","tags":{"Technical":3}},{"text":"Screen resolution and color accuracy.","tags":{"Creative":3}},{"text":"The cheapest one that works.","tags":{"Practical":3}},{"text":"The one all my friends have.","tags":{"Social":2}}]},
        {"text":"How do you feel about coding?","options":[{"text":"I love the logic and problem solving.","tags":{"Technical":3,"Analytical":3}},{"text":"It's a useful tool to build my designs.","tags":{"Creative":2,"Practical":2}},{"text":"It seems boring and too complex.","tags":{"Social":2}},{"text":"I prefer dealing with hardware over software.","tags":{"Technical":2}}]},
        {"text":"When a group project requires a presentation, you:","options":[{"text":"Format the slides to look perfect.","tags":{"Creative":3}},{"text":"Organize the data and research.","tags":{"Analytical":3}},{"text":"Do the actual speaking.","tags":{"Communication":3}},{"text":"Manage the timeline.","tags":{"Organized":3}}]},
        {"text":"If you could master any skill instantly, it would be:","options":[{"text":"Hacking/Cybersecurity.","tags":{"Technical":3,"Analytical":2}},{"text":"Digital Animation.","tags":{"Creative":3}},{"text":"Public Speaking.","tags":{"Communication":3}},{"text":"Advanced Mathematics.","tags":{"Logical":3}}]},
        {"text":"How do you stay updated on news?","options":[{"text":"Tech blogs and forums like Reddit.","tags":{"Technical":3}},{"text":"Social media feeds.","tags":{"Social":3}},{"text":"Traditional news websites.","tags":{"Organized":2}},{"text":"I don't really follow the news.","tags":{"Independent":2}}]},
        {"text":"When setting up a smart home device, you:","options":[{"text":"Integrate it perfectly with my network.","tags":{"Technical":3}},{"text":"Just want it to play music and turn on lights.","tags":{"Practical":3}},{"text":"Worry about it recording my data.","tags":{"Analytical":3}},{"text":"Make it change colors based on my mood.","tags":{"Creative":3}}]},
        {"text":"Which of these sounds most tedious to you?","options":[{"text":"Writing documentation for code.","tags":{"Technical":1,"Creative":3}},{"text":"Debugging a small syntax error.","tags":{"Logical":2}},{"text":"Drawing the same frame 100 times.","tags":{"Analytical":3}},{"text":"Talking to angry customers.","tags":{"Independent":3}}]},
        {"text":"How do you explain Wi-Fi to a child?","options":[{"text":"'Invisible waves that carry internet.'","tags":{"Communication":3,"Creative":2}},{"text":"'Radio frequencies transmitting data.'","tags":{"Technical":3}},{"text":"'Magic that makes YouTube work.'","tags":{"Empathy":2}},{"text":"I wouldn't know how to simplify it.","tags":{"Analytical":2}}]},
        {"text":"What is your favorite part of a video game?","options":[{"text":"The core gameplay mechanics and loops.","tags":{"Analytical":3}},{"text":"The graphics and soundtrack.","tags":{"Creative":3}},{"text":"The storyline and character dialogue.","tags":{"Empathy":2}},{"text":"Playing with my friends online.","tags":{"Social":3}}]},
        {"text":"How do you feel about open-source software?","options":[{"text":"Love it, I want to contribute to the code.","tags":{"Technical":3,"Collaborative":2}},{"text":"It's great because it's free.","tags":{"Practical":3}},{"text":"I prefer polished, paid software.","tags":{"Organized":2}},{"text":"I don't know what that means.","tags":{"Easygoing":1}}]}
    ],
    "ArtMusic": [
        {"text":"When listening to a new song, what grabs your attention first?","options":[{"text":"The lyrical storytelling and emotion.","tags":{"Empathy":3,"Communication":2}},{"text":"The underlying beat and rhythm.","tags":{"Creative":3,"Auditory":3}},{"text":"The technical production and mixing.","tags":{"Analytical":2,"Technical":3}},{"text":"How well I can dance to it.","tags":{"Expressive":3,"Practical":1}}]},
        {"text":"Faced with a blank canvas (or page), you feel:","options":[{"text":"Excited to let my imagination run wild.","tags":{"Imaginative":3,"Creative":3}},{"text":"Anxious until I outline a solid plan.","tags":{"Organized":3,"Analytical":2}},{"text":"Inspired to express a deep personal feeling.","tags":{"Expressive":3,"Empathy":2}},{"text":"Ready to experiment with new tools/brushes.","tags":{"Technical":3,"ProblemSolving":2}}]},
        {"text":"How do you prefer to practice your craft?","options":[{"text":"Jamming or collaborating with others.","tags":{"Social":3,"Communication":3}},{"text":"Isolating myself until it's perfect.","tags":{"Independent":3,"Dedicated":2}},{"text":"Studying the masters and analyzing their work.","tags":{"Analytical":3,"Organized":2}},{"text":"Performing live and feeding off the crowd.","tags":{"Expressive":3,"Leadership":2}}]},
        {"text":"At an art museum, you spend the most time:","options":[{"text":"Looking closely at brushstrokes and techniques.","tags":{"Technical":3,"Visual":3}},{"text":"Reading the history behind the pieces.","tags":{"Analytical":3,"Communication":2}},{"text":"Soaking in the overall mood of the room.","tags":{"Empathy":3,"Creative":2}},{"text":"Looking for interactive or modern exhibits.","tags":{"Practical":2,"Imaginative":3}}]},
        {"text":"If you were to score a film, it would be:","options":[{"text":"A sweeping, emotional orchestral piece.","tags":{"Creative":3,"Empathy":3}},{"text":"A gritty, electronic synthwave track.","tags":{"Technical":3,"Expressive":2}},{"text":"A catchy pop soundtrack.","tags":{"Social":3,"Communication":2}},{"text":"A minimalist, experimental soundscape.","tags":{"Analytical":3,"Imaginative":3}}]},
        {"text":"What is your relationship with criticism?","options":[{"text":"I use it to technically improve my skills.","tags":{"Analytical":3,"Dedicated":3}},{"text":"It hurts, my work is very personal to me.","tags":{"Sensitive":3,"Expressive":2}},{"text":"I debate it if I think my vision was right.","tags":{"Communication":3,"Leadership":2}},{"text":"I ignore it and keep making what I love.","tags":{"Independent":3,"Creative":2}}]},
        {"text":"When designing a poster, what matters most?","options":[{"text":"The typography and alignment.","tags":{"Organized":3,"Technical":2}},{"text":"The striking use of color.","tags":{"Visual":3,"Creative":3}},{"text":"The message it conveys to the audience.","tags":{"Communication":3,"Empathy":2}},{"text":"Getting it done quickly and efficiently.","tags":{"Practical":3}}]},
        {"text":"Your ideal creative workspace is:","options":[{"text":"A messy studio filled with paints and instruments.","tags":{"Creative":3,"Expressive":3}},{"text":"A clean, minimalist desk with a high-end monitor.","tags":{"Organized":3,"Technical":3}},{"text":"A bustling coffee shop.","tags":{"Social":3,"Adaptable":2}},{"text":"Outdoors in nature.","tags":{"Nature":3,"Imaginative":2}}]},
        {"text":"In a coffee shop, you notice first:","options":[{"text":"Furniture, lighting, and wall art.","tags":{"Creative":3,"Visual":3}},{"text":"The background music.","tags":{"Creative":2,"Auditory":3}},{"text":"How fast the line moves.","tags":{"Analytical":2,"Organized":2}},{"text":"The vibe of the people.","tags":{"Empathy":3}}]},
        {"text":"Bored in class, you are likely:","options":[{"text":"Doodling in the margins.","tags":{"Creative":3,"Visual":2}},{"text":"Writing a story or poem.","tags":{"Creative":2,"Communication":3}},{"text":"Daydreaming big ideas.","tags":{"Imaginative":3}},{"text":"Reading ahead.","tags":{"Analytical":3}}]},
        {"text":"Deciding what clothes to wear:","options":[{"text":"Mixing colors and styles.","tags":{"Creative":3,"Expressive":3}},{"text":"Whatever is comfortable.","tags":{"Practical":3}},{"text":"Following current trends.","tags":{"Social":2}},{"text":"Grabbing the first clean thing.","tags":{"Easygoing":2}}]},
        {"text":"When buying a product, you choose based on:","options":[{"text":"Beautiful packaging and design.","tags":{"Creative":3}},{"text":"Best features and specs.","tags":{"Analytical":3,"Technical":2}},{"text":"The cheapest option.","tags":{"Practical":3}},{"text":"Friend recommendations.","tags":{"Communication":2}}]},
        {"text":"Favorite way to express feelings:","options":[{"text":"Drawing, painting, or designing.","tags":{"Creative":3}},{"text":"Writing or talking.","tags":{"Communication":3}},{"text":"Music or acting.","tags":{"Expressive":3}},{"text":"Processing quietly alone.","tags":{"Independent":2}}]},
        {"text":"Which software to master?","options":[{"text":"Adobe Photoshop/Illustrator.","tags":{"Creative":3,"Technical":2}},{"text":"Microsoft Excel.","tags":{"Analytical":3,"Organized":2}},{"text":"Video editing (Premiere).","tags":{"Creative":2,"Technical":2}},{"text":"I don't like complex software.","tags":{"Practical":2}}]},
        {"text":"On a blank billboard, you put:","options":[{"text":"Original artwork.","tags":{"Creative":3}},{"text":"A clever, funny quote.","tags":{"Communication":3,"Empathy":2}},{"text":"A business ad.","tags":{"Logical":2,"Leadership":2}},{"text":"A confusing puzzle.","tags":{"Analytical":3}}]},
        {"text":"When you take a photo, what is most important?","options":[{"text":"The composition and lighting.","tags":{"Creative":3,"Visual":3}},{"text":"Capturing a genuine emotion.","tags":{"Empathy":3,"Expressive":2}},{"text":"Making sure everyone is in frame.","tags":{"Organized":2}},{"text":"I prefer taking videos over photos.","tags":{"Technical":2}}]},
        {"text":"If you redesign your bedroom, you start with:","options":[{"text":"Picking a specific color palette and theme.","tags":{"Creative":3,"Organized":2}},{"text":"Moving furniture for better space and flow.","tags":{"Analytical":2,"Practical":3}},{"text":"Hanging up posters of things I love.","tags":{"Expressive":3}},{"text":"I don't care what my room looks like.","tags":{"Easygoing":3}}]},
        {"text":"What kind of YouTube videos do you binge?","options":[{"text":"Video essays on movies, art, or game design.","tags":{"Analytical":2,"Creative":3}},{"text":"Vlogs and lifestyle content.","tags":{"Social":3}},{"text":"Tech reviews and unboxings.","tags":{"Technical":3}},{"text":"Comedy and sketch shows.","tags":{"Communication":2,"Expressive":2}}]},
        {"text":"If you were a character in a movie, you'd be:","options":[{"text":"The visionary director behind the camera.","tags":{"Leadership":2,"Creative":3}},{"text":"The charismatic lead actor.","tags":{"Expressive":3,"Communication":3}},{"text":"The writer who created the whole universe.","tags":{"Imaginative":3}},{"text":"The brilliant hacker sidekick.","tags":{"Technical":3}}]},
        {"text":"How do you feel about modern abstract art?","options":[{"text":"I love interpreting the hidden meanings.","tags":{"Creative":3,"Analytical":2}},{"text":"I appreciate the colors, even if it's weird.","tags":{"Visual":3}},{"text":"I think it's mostly a scam. Anyone could paint that.","tags":{"Logical":3,"Practical":2}},{"text":"It's okay, but I prefer realistic drawings.","tags":{"Organized":2}}]},
        {"text":"When writing an essay, you spend the most time:","options":[{"text":"Finding the perfect descriptive words.","tags":{"Communication":3,"Creative":2}},{"text":"Making sure the formatting and citations are flawless.","tags":{"Organized":3}},{"text":"Structuring a bulletproof argument.","tags":{"Analytical":3,"Logical":2}},{"text":"Procrastinating until the night before.","tags":{"Adaptable":2}}]},
        {"text":"What is your relationship with social media?","options":[{"text":"I carefully curate my grid to look aesthetic.","tags":{"Creative":3,"Visual":3}},{"text":"I use it to chat and stay connected.","tags":{"Social":3,"Communication":2}},{"text":"I mainly lurk and consume information.","tags":{"Analytical":2}},{"text":"I rarely use it. I prefer real life.","tags":{"Independent":3}}]},
        {"text":"If you had to learn an instrument, it would be:","options":[{"text":"Piano (complex and versatile).","tags":{"Analytical":3,"Creative":2}},{"text":"Electric Guitar (loud and expressive).","tags":{"Expressive":3}},{"text":"Drums (rhythm and energy).","tags":{"Practical":3}},{"text":"Synthesizer (electronic and technical).","tags":{"Technical":3}}]},
        {"text":"How do you sketch or draw?","options":[{"text":"Freehand, letting my imagination guide me.","tags":{"Creative":3,"Imaginative":3}},{"text":"With a ruler, measuring perfect perspective.","tags":{"Organized":3,"Analytical":2}},{"text":"I can only draw stick figures.","tags":{"Practical":2}},{"text":"I trace or copy things I see.","tags":{"Visual":2}}]},
        {"text":"When watching an animated movie, you think about:","options":[{"text":"How many hours it took to render the lighting.","tags":{"Technical":3,"Creative":2}},{"text":"The character design and color choices.","tags":{"Creative":3,"Visual":3}},{"text":"The vocal performances of the actors.","tags":{"Expressive":3}},{"text":"Just enjoying the plot.","tags":{"Easygoing":3}}]}
    ],
    "Healthcare": [
        {"text":"A stranger suddenly faints in a public place. You:","options":[{"text":"Immediately check their pulse and breathing.","tags":{"Practical":3,"ProblemSolving":3}},{"text":"Comfort the people around them and call 911.","tags":{"Empathy":3,"Communication":3}},{"text":"Organize the crowd to give the person space.","tags":{"Leadership":3,"Organized":2}},{"text":"Panic slightly, but try to find a doctor.","tags":{"Sensitive":2,"Resourceful":3}}]},
        {"text":"What aspect of the human body fascinates you most?","options":[{"text":"How the brain processes thoughts and trauma.","tags":{"Psychology":3,"Empathy":2}},{"text":"The mechanics of bones, muscles, and surgery.","tags":{"Technical":3,"Analytical":2}},{"text":"How cells fight off viruses and diseases.","tags":{"Logical":3,"Analytical":3}},{"text":"Diet, nutrition, and holistic wellness.","tags":{"Nature":3,"Practical":3}}]},
        {"text":"How do you deliver difficult news to a friend?","options":[{"text":"With deep empathy, holding their hand.","tags":{"Empathy":3,"Emotional":3}},{"text":"Directly and clearly, offering immediate solutions.","tags":{"Logical":3,"ProblemSolving":2}},{"text":"I try to have someone else do it, I hate conflict.","tags":{"Reserved":3}},{"text":"I carefully script what I'm going to say first.","tags":{"Organized":3,"Communication":2}}]},
        {"text":"Working a 12-hour night shift sounds:","options":[{"text":"Exhausting, but worth it to save lives.","tags":{"Dedicated":3,"Empathy":3}},{"text":"Great, I love the quiet focus of the night.","tags":{"Independent":3,"Analytical":2}},{"text":"Terrible, I need a strict sleep schedule.","tags":{"Organized":3,"Practical":2}},{"text":"Exciting, I thrive on adrenaline and coffee.","tags":{"Adaptable":3,"ProblemSolving":2}}]},
        {"text":"In a hospital setting, you would rather be:","options":[{"text":"The surgeon performing a high-stakes operation.","tags":{"Technical":3,"Leadership":3}},{"text":"The nurse providing daily care and comfort.","tags":{"Empathy":3,"Dedicated":3}},{"text":"The lab technician analyzing blood samples.","tags":{"Analytical":3,"Independent":3}},{"text":"The administrator managing hospital efficiency.","tags":{"Organized":3,"Logical":2}}]},
        {"text":"How do you feel about continuous, lifelong learning?","options":[{"text":"I love reading the latest medical journals.","tags":{"Analytical":3,"Logical":2}},{"text":"I enjoy learning if it directly helps my patients.","tags":{"Empathy":3,"Practical":3}},{"text":"I prefer to master one skill and stick to it.","tags":{"Dedicated":2,"Organized":2}},{"text":"I like learning through hands-on practice.","tags":{"Technical":3,"Adaptable":2}}]},
        {"text":"When someone is dealing with a chronic illness, you:","options":[{"text":"Research alternative treatments and clinical trials.","tags":{"Analytical":3,"Resourceful":3}},{"text":"Check in on their mental health regularly.","tags":{"Psychology":3,"Empathy":3}},{"text":"Cook them meals and help with daily chores.","tags":{"Practical":3,"Dedicated":2}},{"text":"Help them organize their medications and appointments.","tags":{"Organized":3}}]},
        {"text":"How do you handle gross sights (blood, wounds)?","options":[{"text":"I have a strong stomach, it doesn't bother me.","tags":{"Practical":3,"Dedicated":3}},{"text":"I view it purely clinically and scientifically.","tags":{"Analytical":3,"Logical":3}},{"text":"I feel woozy but I push through it.","tags":{"Adaptable":2}},{"text":"I absolutely cannot handle it.","tags":{"Sensitive":3}}]},
        {"text":"A friend is bleeding. You:","options":[{"text":"Stay calm, clean and bandage it.","tags":{"Practical":3,"ProblemSolving":2}},{"text":"Comfort them so they aren't scared.","tags":{"Empathy":3}},{"text":"Faint or look away.","tags":{"Sensitive":3}},{"text":"Call someone who knows what to do.","tags":{"Communication":2}}]},
        {"text":"How do you feel about daily routines?","options":[{"text":"Love having a strict schedule.","tags":{"Organized":3}},{"text":"Like them, but need flexibility.","tags":{"Adaptable":2}},{"text":"Thrive when every day is different.","tags":{"Adaptable":3,"ProblemSolving":2}},{"text":"Hate routines, prefer to wing it.","tags":{"Creative":2}}]},
        {"text":"When a friend has a problem, you:","options":[{"text":"Listen quietly and offer a shoulder.","tags":{"Empathy":3}},{"text":"Offer solutions to fix it.","tags":{"ProblemSolving":3,"Logical":2}},{"text":"Try to distract them with fun.","tags":{"Creative":2,"Social":2}},{"text":"Help them analyze why it happened.","tags":{"Analytical":3}}]},
        {"text":"Working under extreme pressure:","options":[{"text":"I stay highly focused and act quickly.","tags":{"ProblemSolving":3,"Leadership":2}},{"text":"I get anxious but push through.","tags":{"Dedicated":3}},{"text":"I need to step back and breathe.","tags":{"Analytical":2}},{"text":"I prefer low-stress environments.","tags":{"Creative":2}}]},
        {"text":"Comfortable talking to strangers?","options":[{"text":"Yes, I love making people feel heard.","tags":{"Empathy":3,"Communication":3}},{"text":"Only if I have a reason to.","tags":{"Logical":2,"Practical":2}},{"text":"Can do it, but it drains me.","tags":{"Independent":2}},{"text":"No, I am very shy.","tags":{"Reserved":2}}]},
        {"text":"If you see a stray animal on the street, you:","options":[{"text":"Try to catch it and take it to a vet/shelter.","tags":{"Empathy":3,"Nature":3}},{"text":"Call animal control to handle it safely.","tags":{"Organized":2,"Logical":2}},{"text":"Feel sad but keep walking.","tags":{"Sensitive":2}},{"text":"Try to feed it from a distance.","tags":{"Practical":2}}]},
        {"text":"What is your approach to eating healthy?","options":[{"text":"I track my macros and calories in an app.","tags":{"Analytical":3,"Organized":3}},{"text":"I eat intuitively based on how my body feels.","tags":{"Empathy":2,"Adaptable":2}},{"text":"I love cooking fresh, organic meals from scratch.","tags":{"Creative":3,"Nature":2}},{"text":"I eat whatever tastes good and is cheap.","tags":{"Practical":3}}]},
        {"text":"When someone is grieving, the best thing to do is:","options":[{"text":"Sit with them in silence and hold their hand.","tags":{"Empathy":3,"Emotional":3}},{"text":"Cook them meals and clean their house.","tags":{"Practical":3,"Dedicated":2}},{"text":"Give them space to process it alone.","tags":{"Independent":2}},{"text":"Recommend a good therapist.","tags":{"Analytical":2,"Logical":2}}]},
        {"text":"How is your memory for small details?","options":[{"text":"Excellent, I remember allergies and birthdays.","tags":{"Empathy":3,"Organized":3}},{"text":"Good for facts and numbers, bad for names.","tags":{"Analytical":3}},{"text":"Terrible, I have to write everything down.","tags":{"Adaptable":2}},{"text":"I only remember things I find interesting.","tags":{"Creative":2}}]},
        {"text":"How do you feel about physical fitness?","options":[{"text":"I love pushing my body to its absolute limits.","tags":{"Dedicated":3,"Practical":2}},{"text":"I enjoy yoga and stretching for mental clarity.","tags":{"Empathy":2,"Nature":2}},{"text":"I analyze fitness science and optimize workouts.","tags":{"Analytical":3,"Technical":2}},{"text":"I hate sweating.","tags":{"Easygoing":3}}]},
        {"text":"If a child is throwing a tantrum in public, you think:","options":[{"text":"'That poor parent must be so stressed.'","tags":{"Empathy":3}},{"text":"'I wonder what triggered the child's behavior.'","tags":{"Analytical":3,"Psychology":3}},{"text":"'Someone needs to discipline that kid.'","tags":{"Logical":2}},{"text":"'I need to get out of this store right now.'","tags":{"Independent":3}}]},
        {"text":"How do you handle sleep deprivation?","options":[{"text":"I can push through it with coffee and adrenaline.","tags":{"Dedicated":3,"Adaptable":2}},{"text":"I become very cranky and useless.","tags":{"Sensitive":3}},{"text":"I refuse to get less than 8 hours, it's unhealthy.","tags":{"Organized":3,"Logical":2}},{"text":"I take strategic power naps.","tags":{"Analytical":3}}]},
        {"text":"What is your view on mental health?","options":[{"text":"It is just as important as physical health.","tags":{"Empathy":3,"Logical":2}},{"text":"It can be solved by changing chemical imbalances.","tags":{"Analytical":3,"Technical":2}},{"text":"Nature and meditation are the best cures.","tags":{"Nature":3}},{"text":"People just need to toughen up.","tags":{"Practical":2,"Logical":1}}]},
        {"text":"How do you react when you get sick?","options":[{"text":"I research my symptoms extensively online.","tags":{"Analytical":3}},{"text":"I follow the doctor's orders perfectly.","tags":{"Organized":3}},{"text":"I drink tea, sleep, and use natural remedies.","tags":{"Nature":3,"Practical":2}},{"text":"I ignore it and keep going to work.","tags":{"Dedicated":3}}]},
        {"text":"When learning a physical task (like giving CPR), you:","options":[{"text":"Practice repeatedly on a dummy until perfect.","tags":{"Dedicated":3,"Practical":3}},{"text":"Memorize the textbook steps first.","tags":{"Analytical":3,"Organized":2}},{"text":"Ask the instructor to watch and correct my form.","tags":{"Communication":3}},{"text":"Hope I never actually have to use it.","tags":{"Sensitive":2}}]},
        {"text":"What do you think of alternative medicine (like acupuncture)?","options":[{"text":"If it makes the patient feel better, it's good.","tags":{"Empathy":3,"OpenMinded":3}},{"text":"It's a scam without peer-reviewed scientific proof.","tags":{"Logical":3,"Analytical":3}},{"text":"I want to learn how to do it.","tags":{"Creative":2,"Practical":2}},{"text":"I'm scared of needles.","tags":{"Sensitive":2}}]},
        {"text":"How good are you at multitasking in a chaotic room?","options":[{"text":"Excellent, I thrive when 5 things happen at once.","tags":{"Adaptable":3,"ProblemSolving":3}},{"text":"I can do it, but I make checklists to stay sane.","tags":{"Organized":3}},{"text":"Terrible. I need quiet to focus on one patient.","tags":{"Analytical":2,"Sensitive":2}},{"text":"I delegate the tasks to other people.","tags":{"Leadership":3}}]}
    ],
    "GovServices": [
        {"text":"When you see a pothole in your neighborhood, you:","options":[{"text":"Organize a petition to get the city to fix it.","tags":{"Leadership":3,"Communication":3}},{"text":"Research the city budget to see why roads are failing.","tags":{"Analytical":3,"Logical":2}},{"text":"Fill it with gravel yourself to help out.","tags":{"Practical":3,"ProblemSolving":2}},{"text":"Complain about it on social media.","tags":{"Expressive":2}}]},
        {"text":"What is the most important role of a government?","options":[{"text":"Maintaining law, order, and national security.","tags":{"Logical":3,"Organized":3}},{"text":"Providing welfare and protecting the vulnerable.","tags":{"Empathy":3,"Social":3}},{"text":"Building infrastructure (roads, schools, grids).","tags":{"Technical":3,"Practical":2}},{"text":"Balancing the budget and managing the economy.","tags":{"Analytical":3,"ProblemSolving":2}}]},
        {"text":"If a natural disaster strikes your city, you are the one who:","options":[{"text":"Coordinates the rescue volunteers.","tags":{"Leadership":3,"Organized":3}},{"text":"Operates the heavy machinery to clear debris.","tags":{"Technical":3,"Practical":3}},{"text":"Distributes food and blankets to victims.","tags":{"Empathy":3,"Dedicated":2}},{"text":"Analyzes the structural damage of buildings.","tags":{"Analytical":3,"Logical":2}}]},
        {"text":"How do you feel about working within strict bureaucracies?","options":[{"text":"I excel at navigating complex rules and forms.","tags":{"Organized":3,"Analytical":3}},{"text":"I find loopholes to get things done faster.","tags":{"ProblemSolving":3,"Resourceful":3}},{"text":"I hate the red tape, I want to change the system.","tags":{"Leadership":3,"Creative":2}},{"text":"I just follow instructions to avoid trouble.","tags":{"Practical":2,"Easygoing":2}}]},
        {"text":"Which historical figure do you admire most?","options":[{"text":"A military general who won a strategic war.","tags":{"Leadership":3,"Logical":3}},{"text":"A civil rights leader who changed society.","tags":{"Communication":3,"Empathy":3}},{"text":"An engineer who built a famous dam or bridge.","tags":{"Technical":3,"Practical":2}},{"text":"A diplomat who negotiated a lasting peace treaty.","tags":{"Analytical":3,"ProblemSolving":3}}]},
        {"text":"In a public town hall meeting, you would:","options":[{"text":"Give a passionate speech at the microphone.","tags":{"Communication":3,"Expressive":3}},{"text":"Take detailed notes on community concerns.","tags":{"Organized":3,"Empathy":2}},{"text":"Present a data-driven slideshow on taxes.","tags":{"Analytical":3,"Logical":2}},{"text":"Stand in the back and observe the crowd.","tags":{"Independent":2,"Observation":3}}]},
        {"text":"Your approach to urban planning is:","options":[{"text":"Focusing on green spaces and environmental impact.","tags":{"Nature":3,"Empathy":2}},{"text":"Optimizing traffic flow and public transit.","tags":{"Logical":3,"Technical":3}},{"text":"Ensuring affordable housing for low-income families.","tags":{"Social":3,"Empathy":3}},{"text":"Attracting big businesses to boost the economy.","tags":{"Leadership":3,"Analytical":2}}]},
        {"text":"What motivates you to choose a career in public service?","options":[{"text":"The desire to leave a lasting, positive legacy.","tags":{"Leadership":3,"Dedicated":3}},{"text":"The stability, benefits, and pension.","tags":{"Practical":3,"Organized":2}},{"text":"A deep sense of duty to my country/community.","tags":{"Empathy":3,"Logical":2}},{"text":"The opportunity to manage massive, complex systems.","tags":{"Analytical":3,"Technical":2}}]},
        {"text":"If you were a city mayor, what is your first project?","options":[{"text":"Expanding public parks and planting trees.","tags":{"Nature":3,"Empathy":2}},{"text":"Increasing funding for the police and fire departments.","tags":{"Logical":3,"Leadership":2}},{"text":"Digitizing all city records to eliminate paper.","tags":{"Technical":3,"Organized":2}},{"text":"Creating a task force for homelessness.","tags":{"Social":3,"ProblemSolving":2}}]},
        {"text":"How do you handle a conflict between two neighboring towns?","options":[{"text":"Review the state laws to see who has legal authority.","tags":{"Analytical":3,"Logical":3}},{"text":"Host a joint dinner to build relationships between leaders.","tags":{"Communication":3,"Social":3}},{"text":"Propose a financial compromise that benefits both.","tags":{"ProblemSolving":3,"Practical":2}},{"text":"Let them figure it out themselves.","tags":{"Independent":2}}]},
        {"text":"When analyzing a new proposed law, you look at:","options":[{"text":"How it affects the poorest citizens.","tags":{"Empathy":3,"Social":3}},{"text":"How much it will cost the taxpayers.","tags":{"Analytical":3,"Logical":2}},{"text":"Whether it is enforceable in the real world.","tags":{"Practical":3,"Organized":2}},{"text":"If it aligns with historical constitutional intent.","tags":{"Logical":3,"Analytical":2}}]},
        {"text":"What kind of intelligence work appeals to you?","options":[{"text":"Analyzing satellite imagery and intercepting codes.","tags":{"Technical":3,"Analytical":3}},{"text":"Working undercover to gather human intelligence.","tags":{"RiskTaking":3,"Communication":3}},{"text":"Writing policy briefings for the President.","tags":{"Organized":3,"Communication":2}},{"text":"Managing the logistics of an overseas base.","tags":{"Practical":3,"Organized":2}}]},
        {"text":"How do you feel about taxes?","options":[{"text":"They are a necessary pool of resources for the greater good.","tags":{"Social":3,"Empathy":2}},{"text":"They are too high and stifle economic growth.","tags":{"Logical":3,"Practical":2}},{"text":"They are too complicated and need a total redesign.","tags":{"ProblemSolving":3,"Analytical":2}},{"text":"I just pay them and don't think about it.","tags":{"Easygoing":3}}]},
        {"text":"If you worked in an embassy abroad, you would want to:","options":[{"text":"Host cultural events to share your nation's art/music.","tags":{"Creative":3,"Social":3}},{"text":"Negotiate trade deals with foreign ministers.","tags":{"Communication":3,"Logical":2}},{"text":"Process visas and help citizens in trouble.","tags":{"Organized":3,"Empathy":2}},{"text":"Ensure the physical security of the compound.","tags":{"Practical":3,"Dedicated":2}}]},
        {"text":"How do you respond to public criticism?","options":[{"text":"I release a detailed fact-sheet to clear up misconceptions.","tags":{"Analytical":3,"Organized":2}},{"text":"I hold a press conference to control the narrative.","tags":{"Communication":3,"Leadership":3}},{"text":"I ignore it and let my actions speak for themselves.","tags":{"Independent":3,"Dedicated":2}},{"text":"I get defensive and try to find out who started it.","tags":{"Sensitive":2}}]},
        {"text":"What is the biggest threat to modern society?","options":[{"text":"Cyberattacks on critical infrastructure.","tags":{"Technical":3,"Analytical":2}},{"text":"Climate change and natural resource depletion.","tags":{"Nature":3,"ProblemSolving":2}},{"text":"Wealth inequality and social division.","tags":{"Empathy":3,"Social":3}},{"text":"Political corruption and lack of leadership.","tags":{"Logical":3,"Leadership":2}}]},
        {"text":"When organizing a massive public event (like an election), you:","options":[{"text":"Design the secure database to count the votes.","tags":{"Technical":3,"Organized":3}},{"text":"Manage the volunteers at the polling stations.","tags":{"Leadership":3,"Communication":3}},{"text":"Ensure elderly and disabled people have access.","tags":{"Empathy":3,"Practical":2}},{"text":"Handle the physical setup of the voting booths.","tags":{"Practical":3}}]},
        {"text":"If you were a whistleblower, you would do it because:","options":[{"text":"The rules were broken and justice must be served.","tags":{"Logical":3,"Dedicated":3}},{"text":"People were being hurt by the cover-up.","tags":{"Empathy":3,"Social":3}},{"text":"I calculated that the truth would come out anyway.","tags":{"Analytical":3,"Practical":2}},{"text":"I wouldn't do it, I'd stay quiet to protect my job.","tags":{"Reserved":3}}]},
        {"text":"What is your view on public transportation?","options":[{"text":"It needs high-speed rail and better engineering.","tags":{"Technical":3,"ProblemSolving":2}},{"text":"It should be completely free for all citizens.","tags":{"Empathy":3,"Social":3}},{"text":"It needs better scheduling and fiscal management.","tags":{"Organized":3,"Analytical":2}},{"text":"I prefer driving my own car.","tags":{"Independent":3}}]},
        {"text":"When drafting a speech for a politician, you focus on:","options":[{"text":"Inspiring words that unite the audience.","tags":{"Communication":3,"Creative":3}},{"text":"Clear, hard facts that prove the policy works.","tags":{"Analytical":3,"Logical":2}},{"text":"Bullet points that outline exactly what will happen next.","tags":{"Organized":3,"Practical":2}},{"text":"I'd rather be the one giving the speech, not writing it.","tags":{"Leadership":3,"Expressive":3}}]},
        {"text":"How do you handle a crisis where resources are limited?","options":[{"text":"I create a strict rationing system based on math.","tags":{"Analytical":3,"Logical":3}},{"text":"I give to the most vulnerable (children, sick) first.","tags":{"Empathy":3,"Social":3}},{"text":"I try to find a creative way to generate more resources.","tags":{"ProblemSolving":3,"Resourceful":3}},{"text":"I take charge and make the tough calls nobody else will.","tags":{"Leadership":3,"Dedicated":2}}]},
        {"text":"What branch of the military interests you most?","options":[{"text":"Cyber Command (Defending networks).","tags":{"Technical":3,"Analytical":3}},{"text":"Army/Marines (Physical discipline and leadership).","tags":{"Dedicated":3,"Leadership":3}},{"text":"Corps of Engineers (Building infrastructure).","tags":{"Practical":3,"ProblemSolving":2}},{"text":"Medical Corps (Treating wounded soldiers).","tags":{"Empathy":3,"Healthcare":2}}]},
        {"text":"If you could pass one universal law, it would be:","options":[{"text":"Mandatory recycling and zero-emissions.","tags":{"Nature":3,"Logical":2}},{"text":"Universal basic income for everyone.","tags":{"Empathy":3,"Social":3}},{"text":"Free high-speed internet globally.","tags":{"Technical":3,"Communication":2}},{"text":"Strict transparency for all government spending.","tags":{"Analytical":3,"Organized":3}}]},
        {"text":"How do you interact with your local community?","options":[{"text":"I attend city council meetings and vote in every local election.","tags":{"Organized":3,"Logical":2}},{"text":"I volunteer at the local food bank or shelter.","tags":{"Empathy":3,"Social":3}},{"text":"I organize neighborhood block parties and events.","tags":{"Communication":3,"Leadership":2}},{"text":"I mostly keep to myself.","tags":{"Independent":3}}]},
        {"text":"What is the most challenging part of public service?","options":[{"text":"Dealing with angry, irrational citizens.","tags":{"Sensitive":3,"Communication":2}},{"text":"The slow, frustrating pace of getting anything approved.","tags":{"Practical":3,"ProblemSolving":3}},{"text":"The heavy emotional burden of seeing people struggle.","tags":{"Empathy":3,"Dedicated":2}},{"text":"Keeping track of changing laws and regulations.","tags":{"Analytical":3,"Organized":2}}]}
    ],
    "Entrepreneurship": [
        {"text":"You have $5,000 to invest. You:","options":[{"text":"Put it all into a high-risk, high-reward startup.","tags":{"RiskTaking":3,"Leadership":3}},{"text":"Invest it safely in an index fund for steady growth.","tags":{"Analytical":3,"Organized":2}},{"text":"Use it to buy inventory to start a side hustle.","tags":{"Practical":3,"ProblemSolving":3}},{"text":"Spend it on a marketing course to learn new skills.","tags":{"Resourceful":3,"Communication":2}}]},
        {"text":"When pitching a new idea to someone, you rely on:","options":[{"text":"Charisma, storytelling, and painting a vision.","tags":{"Communication":3,"Expressive":3}},{"text":"Hard data, market research, and spreadsheets.","tags":{"Analytical":3,"Logical":3}},{"text":"Showing them a physical prototype that works.","tags":{"Technical":3,"Practical":3}},{"text":"Highlighting how it helps people and solves pain points.","tags":{"Empathy":3,"Social":2}}]},
        {"text":"How do you handle failure?","options":[{"text":"I pivot immediately and try a new angle.","tags":{"Adaptable":3,"ProblemSolving":3}},{"text":"I analyze exactly what went wrong so it never happens again.","tags":{"Analytical":3,"Organized":3}},{"text":"I take it very personally and need time to recover.","tags":{"Sensitive":3}},{"text":"I use it as motivation to prove my doubters wrong.","tags":{"Leadership":3,"Dedicated":3}}]},
        {"text":"Your ideal Friday night involves:","options":[{"text":"Networking at a local business mixer.","tags":{"Social":3,"Communication":3}},{"text":"Coding or building out my personal website.","tags":{"Technical":3,"Independent":3}},{"text":"Reading a biography of a successful billionaire.","tags":{"Analytical":2,"Leadership":3}},{"text":"Relaxing, I strictly separate work and life.","tags":{"Easygoing":3,"Practical":2}}]},
        {"text":"If you were building a founding team, you would be the:","options":[{"text":"Hustler (Sales, Marketing, Vision).","tags":{"Communication":3,"Leadership":3}},{"text":"Hacker (Building the product, Coding).","tags":{"Technical":3,"ProblemSolving":3}},{"text":"Hipster (Design, Branding, UX).","tags":{"Creative":3,"Visual":3}},{"text":"Hound (Finance, Operations, Logistics).","tags":{"Organized":3,"Analytical":3}}]},
        {"text":"How do you view your competitors?","options":[{"text":"I study them obsessively to find their weaknesses.","tags":{"Analytical":3,"Logical":3}},{"text":"I want to crush them and dominate the market.","tags":{"Leadership":3,"RiskTaking":2}},{"text":"I ignore them and focus on making my product unique.","tags":{"Independent":3,"Creative":3}},{"text":"I try to partner with them for mutual benefit.","tags":{"Communication":3,"Adaptable":3}}]},
        {"text":"When setting prices for a product, you:","options":[{"text":"Calculate the exact cost of goods plus a 20% margin.","tags":{"Analytical":3,"Organized":3}},{"text":"Price it high to create a premium, luxury brand.","tags":{"Creative":3,"Psychology":2}},{"text":"Price it as low as possible to get maximum users.","tags":{"Practical":3,"Logical":2}},{"text":"Ask customers what they are willing to pay.","tags":{"Empathy":3,"Communication":3}}]},
        {"text":"What sounds like the biggest nightmare to you?","options":[{"text":"Working a boring 9-to-5 job for 40 years.","tags":{"RiskTaking":3,"Creative":3}},{"text":"Going bankrupt because of a bad business decision.","tags":{"Organized":3,"Analytical":2}},{"text":"Having to fire an employee who is a good friend.","tags":{"Empathy":3,"Social":3}},{"text":"Spending all day dealing with taxes and lawyers.","tags":{"Practical":3,"Technical":2}}]},
        {"text":"When starting a project, your first step is:","options":[{"text":"Registering the domain name and designing a logo.","tags":{"Creative":3,"Visual":2}},{"text":"Creating a detailed business plan and financial model.","tags":{"Analytical":3,"Organized":3}},{"text":"Talking to potential customers to see if they want it.","tags":{"Communication":3,"Empathy":2}},{"text":"Building a quick, ugly prototype to test the mechanics.","tags":{"Practical":3,"Technical":3}}]},
        {"text":"How do you prefer to manage a team?","options":[{"text":"Set clear KPIs and let them work independently.","tags":{"Organized":3,"Analytical":2}},{"text":"Lead from the front, working longer hours than anyone.","tags":{"Dedicated":3,"Leadership":3}},{"text":"Act as a mentor, focusing on their personal growth.","tags":{"Empathy":3,"Communication":2}},{"text":"I prefer to work completely solo.","tags":{"Independent":3}}]},
        {"text":"What is the best way to market a product?","options":[{"text":"Viral, funny TikToks and social media stunts.","tags":{"Creative":3,"Communication":3}},{"text":"Highly targeted, data-driven Facebook ads.","tags":{"Analytical":3,"Technical":2}},{"text":"Word of mouth by building a genuinely helpful product.","tags":{"Empathy":3,"Social":2}},{"text":"Cold calling and aggressive B2B sales.","tags":{"Leadership":3,"Dedicated":2}}]},
        {"text":"How do you view money?","options":[{"text":"It is a tool to buy freedom and independence.","tags":{"Independent":3,"Logical":2}},{"text":"It is a scoreboard to show how well I am doing.","tags":{"Leadership":3,"Analytical":2}},{"text":"It is fuel to scale my ideas to the moon.","tags":{"RiskTaking":3,"Imaginative":3}},{"text":"It is a resource to help my family and community.","tags":{"Empathy":3,"Social":2}}]},
        {"text":"If an investor offers you $1 Million for 50% of your company, you:","options":[{"text":"Take it! The money will let me grow instantly.","tags":{"Practical":3,"Adaptable":2}},{"text":"Reject it. I want to own 100% of my vision.","tags":{"Independent":3,"Leadership":3}},{"text":"Counter-offer using financial projections to prove my worth.","tags":{"Analytical":3,"Logical":3}},{"text":"Ask to consult with my team and mentors first.","tags":{"Communication":3,"Organized":2}}]},
        {"text":"What book genre do you prefer?","options":[{"text":"Self-help and productivity hacks.","tags":{"Organized":3,"Practical":2}},{"text":"Psychology and human behavior.","tags":{"Psychology":3,"Empathy":2}},{"text":"Biographies of ruthless historical conquerors.","tags":{"Leadership":3,"Logical":2}},{"text":"Sci-fi featuring futuristic technology.","tags":{"Imaginative":3,"Technical":2}}]},
        {"text":"When a customer complains, you:","options":[{"text":"Refund them immediately to protect my brand's reputation.","tags":{"Empathy":3,"Communication":2}},{"text":"Analyze the complaint to fix the root bug in the system.","tags":{"Analytical":3,"ProblemSolving":3}},{"text":"Argue with them if I know my product isn't broken.","tags":{"Logical":3,"Defensive":2}},{"text":"Delegate customer service to someone else.","tags":{"Leadership":2,"Organized":2}}]},
        {"text":"What is your stance on taking risks?","options":[{"text":"I love taking massive risks if the upside is huge.","tags":{"RiskTaking":3,"Adaptable":2}},{"text":"I only take heavily calculated, data-backed risks.","tags":{"Analytical":3,"Logical":3}},{"text":"I prefer slow, steady, and guaranteed growth.","tags":{"Organized":3,"Practical":3}},{"text":"I hate risk and avoid it at all costs.","tags":{"Reserved":3}}]},
        {"text":"If you had to choose a superpower for business, it would be:","options":[{"text":"Reading minds (to know what customers want).","tags":{"Empathy":3,"Psychology":3}},{"text":"Seeing the future (to predict market trends).","tags":{"Analytical":3,"Imaginative":3}},{"text":"Mind control (to close any sale).","tags":{"Leadership":3,"Communication":3}},{"text":"Super speed (to outwork everyone else).","tags":{"Dedicated":3,"Practical":2}}]},
        {"text":"How do you feel about public speaking or pitching?","options":[{"text":"I thrive on it. I love being on stage.","tags":{"Communication":3,"Expressive":3}},{"text":"I get nervous, but I practice until I'm perfect.","tags":{"Dedicated":3,"Organized":2}},{"text":"I hate it. I'd rather build the tech in the background.","tags":{"Independent":3,"Technical":3}},{"text":"I prefer 1-on-1 conversations over large crowds.","tags":{"Empathy":3,"Social":2}}]},
        {"text":"What is the main reason startups fail?","options":[{"text":"They run out of cash due to poor financial planning.","tags":{"Analytical":3,"Organized":3}},{"text":"They build a product nobody actually wants.","tags":{"Empathy":3,"Social":2}},{"text":"The founders give up too easily when it gets hard.","tags":{"Dedicated":3,"Leadership":2}},{"text":"Their technology is faulty or too slow.","tags":{"Technical":3,"ProblemSolving":2}}]},
        {"text":"When you have a great idea in the shower, you:","options":[{"text":"Immediately start coding or sketching it out.","tags":{"Practical":3,"Creative":3}},{"text":"Write it in my notes app and research the market size later.","tags":{"Organized":3,"Analytical":2}},{"text":"Call my best friend to pitch it to them.","tags":{"Communication":3,"Social":2}},{"text":"Forget it by the time I dry off.","tags":{"Easygoing":3}}]},
        {"text":"How do you handle multiple projects at once?","options":[{"text":"I use advanced project management software (Jira, Asana).","tags":{"Organized":3,"Technical":2}},{"text":"I focus obsessively on one until it's done, then move on.","tags":{"Dedicated":3,"Independent":2}},{"text":"I delegate the smaller ones to freelancers.","tags":{"Leadership":3,"Resourceful":3}},{"text":"I thrive in chaos and jump between them based on mood.","tags":{"Adaptable":3,"Creative":2}}]},
        {"text":"What is your approach to networking?","options":[{"text":"I carefully target industry leaders on LinkedIn.","tags":{"Analytical":3,"Organized":2}},{"text":"I go to parties and make friends naturally.","tags":{"Social":3,"Communication":3}},{"text":"I prefer to let my work attract people to me.","tags":{"Independent":3,"Practical":2}},{"text":"I try to help others first without expecting a return.","tags":{"Empathy":3,"Social":2}}]},
        {"text":"If your business started failing, you would:","options":[{"text":"Cut all expenses to the bone to survive.","tags":{"Logical":3,"Organized":3}},{"text":"Double down on marketing to force growth.","tags":{"RiskTaking":3,"Leadership":2}},{"text":"Pivot entirely to a new product line.","tags":{"Adaptable":3,"ProblemSolving":3}},{"text":"Sell the assets and start fresh.","tags":{"Practical":3,"Analytical":2}}]},
        {"text":"What does success look like to you in 10 years?","options":[{"text":"Ringing the bell at the New York Stock Exchange.","tags":{"Leadership":3,"RiskTaking":2}},{"text":"Having a small, highly profitable lifestyle business on a beach.","tags":{"Independent":3,"Easygoing":3}},{"text":"Changing the world with a sustainable, green product.","tags":{"Empathy":3,"Nature":2}},{"text":"Selling my tech to a major company like Google.","tags":{"Technical":3,"Analytical":2}}]},
        {"text":"How do you react to a team member who is underperforming?","options":[{"text":"Fire them quickly. It's just business.","tags":{"Logical":3,"Leadership":2}},{"text":"Put them on a strict performance improvement plan.","tags":{"Organized":3,"Analytical":2}},{"text":"Have a deep conversation to see what's wrong in their personal life.","tags":{"Empathy":3,"Communication":3}},{"text":"Move them to a different role where they might fit better.","tags":{"ProblemSolving":3,"Adaptable":2}}]}
    ],
    "Law": [
        {"text":"Two friends are arguing over a misunderstanding. You:","options":[{"text":"Analyze the facts and timeline to see who is right.","tags":{"Analytical":3,"Logical":3}},{"text":"Mediate and find a compromise so everyone is happy.","tags":{"Empathy":3,"Communication":3}},{"text":"Stay completely out of it.","tags":{"Independent":3,"Reserved":2}},{"text":"Use their argument to your advantage.","tags":{"ProblemSolving":3,"Leadership":2}}]},
        {"text":"When you sign a new app's Terms of Service, you:","options":[{"text":"Skim it quickly for data privacy clauses.","tags":{"Analytical":3,"Resourceful":2}},{"text":"Actually read the fine print carefully.","tags":{"Organized":3,"Dedicated":3}},{"text":"Scroll to the bottom and hit 'Accept' immediately.","tags":{"Practical":3,"Easygoing":3}},{"text":"Refuse to sign if it looks remotely suspicious.","tags":{"Logical":3,"Independent":2}}]},
        {"text":"If you were in a courtroom, which role appeals to you most?","options":[{"text":"The Judge, making the final, impartial decision.","tags":{"Leadership":3,"Logical":3}},{"text":"The Trial Lawyer, delivering a passionate closing argument.","tags":{"Communication":3,"Expressive":3}},{"text":"The Paralegal, finding the hidden loophole in the documents.","tags":{"Analytical":3,"Organized":3}},{"text":"The Expert Witness, explaining complex science to the jury.","tags":{"Technical":3,"Edu":3}}]},
        {"text":"How do you win a debate?","options":[{"text":"By presenting undeniable statistics and precedents.","tags":{"Logical":3,"Analytical":3}},{"text":"By appealing to the audience's morals and emotions.","tags":{"Communication":3,"Empathy":3}},{"text":"By aggressively poking holes in the opponent's logic.","tags":{"ProblemSolving":3,"Leadership":3}},{"text":"I don't debate; I prefer writing persuasive essays.","tags":{"Independent":3,"Organized":2}}]},
        {"text":"What is your view on the justice system?","options":[{"text":"It should focus heavily on rehabilitation and a second chance.","tags":{"Empathy":3,"Social":3}},{"text":"It must be strict to maintain order in society.","tags":{"Logical":3,"Organized":3}},{"text":"It's a complex game of strategy and negotiation.","tags":{"Analytical":3,"ProblemSolving":3}},{"text":"It needs to be completely rewritten to be fair.","tags":{"Creative":3,"Leadership":2}}]},
        {"text":"When negotiating a salary or buying a car, you:","options":[{"text":"Research market value extensively before speaking.","tags":{"Analytical":3,"Organized":3}},{"text":"Charm the other person into giving me a good deal.","tags":{"Communication":3,"Social":3}},{"text":"Set a hard walk-away number and don't budge.","tags":{"Logical":3,"Leadership":3}},{"text":"Get anxious and usually take the first offer.","tags":{"Sensitive":3,"Reserved":2}}]},
        {"text":"How do you handle a massive, boring pile of paperwork?","options":[{"text":"I create a highly organized filing system to tackle it.","tags":{"Organized":3,"Dedicated":3}},{"text":"I speed-read through it looking only for red flags.","tags":{"Analytical":3,"Practical":3}},{"text":"I procrastinate until the absolute deadline.","tags":{"Adaptable":2,"Creative":2}},{"text":"I digitize and automate the data entry process.","tags":{"Technical":3,"ProblemSolving":3}}]},
        {"text":"Someone breaks a minor rule, but for a morally good reason. You:","options":[{"text":"Report them; the law is the law, no exceptions.","tags":{"Logical":3,"Organized":3}},{"text":"Defend them; ethics are more important than strict rules.","tags":{"Empathy":3,"Communication":3}},{"text":"Look for a legal loophole to get them out of trouble.","tags":{"Analytical":3,"ProblemSolving":3}},{"text":"Ignore it, it's none of my business.","tags":{"Practical":3,"Independent":3}}]},
        {"text":"What type of true crime documentary do you prefer?","options":[{"text":"Deep dives into forensic science and DNA.","tags":{"Technical":3,"Analytical":2}},{"text":"Psychological profiles of the criminals.","tags":{"Psychology":3,"Empathy":2}},{"text":"Courtroom dramas about the legal trial process.","tags":{"Logical":3,"Communication":2}},{"text":"Stories about systemic corruption being exposed.","tags":{"Leadership":3,"ProblemSolving":2}}]},
        {"text":"When a friend asks you for advice on a difficult decision, you:","options":[{"text":"Outline the pros and cons logically.","tags":{"Analytical":3,"Logical":3}},{"text":"Ask them how they *feel* about the options.","tags":{"Empathy":3,"Communication":2}},{"text":"Tell them exactly what they should do based on rules.","tags":{"Leadership":3,"Organized":2}},{"text":"Help them brainstorm a creative third option.","tags":{"ProblemSolving":3,"Creative":2}}]},
        {"text":"If you witnessed a crime, you would:","options":[{"text":"Memorize the suspect's description and license plate.","tags":{"Analytical":3,"Observation":3}},{"text":"Rush in to try and stop it.","tags":{"Leadership":3,"RiskTaking":3}},{"text":"Check to see if the victim is okay first.","tags":{"Empathy":3,"Social":2}},{"text":"Record it on my phone for undeniable evidence.","tags":{"Technical":3,"Practical":2}}]},
        {"text":"How do you feel about keeping secrets?","options":[{"text":"I am a vault. I never tell anyone, period.","tags":{"Logical":3,"Dedicated":3}},{"text":"I keep them, unless withholding it hurts someone else.","tags":{"Empathy":3,"Analytical":2}},{"text":"I usually end up telling one trusted friend.","tags":{"Communication":3,"Social":2}},{"text":"I forget the secret within an hour anyway.","tags":{"Easygoing":3}}]},
        {"text":"Your preferred method of professional communication is:","options":[{"text":"A formally formatted, highly precise email.","tags":{"Organized":3,"Logical":3}},{"text":"A quick phone call to negotiate it verbally.","tags":{"Communication":3,"Adaptable":2}},{"text":"A face-to-face meeting over coffee.","tags":{"Social":3,"Empathy":2}},{"text":"Instant messaging (Slack/Teams).","tags":{"Technical":2,"Practical":3}}]},
        {"text":"When analyzing a complex document, you:","options":[{"text":"Highlight every definition and key term.","tags":{"Organized":3,"Analytical":3}},{"text":"Look for contradictory statements to exploit.","tags":{"ProblemSolving":3,"Logical":3}},{"text":"Focus on the overarching intent of the author.","tags":{"Empathy":2,"Communication":3}},{"text":"Use an AI tool to summarize it for me.","tags":{"Technical":3,"Resourceful":3}}]},
        {"text":"If you ran a law firm, your specialty would be:","options":[{"text":"Corporate Mergers and Tax Law.","tags":{"Analytical":3,"Organized":3}},{"text":"Civil Rights and Public Defender work.","tags":{"Empathy":3,"Social":3}},{"text":"Intellectual Property and Tech Patents.","tags":{"Technical":3,"Creative":2}},{"text":"High-profile Criminal Defense.","tags":{"Communication":3,"RiskTaking":3}}]},
        {"text":"How do you handle being proven wrong in an argument?","options":[{"text":"I concede gracefully if their evidence is better.","tags":{"Logical":3,"Analytical":3}},{"text":"I get defensive and try to pivot the topic.","tags":{"Defensive":3,"Communication":2}},{"text":"I apologize for misunderstanding their feelings.","tags":{"Empathy":3,"Social":2}},{"text":"I refuse to admit defeat.","tags":{"Leadership":2,"Dedicated":3}}]},
        {"text":"What is the most important skill for a lawyer?","options":[{"text":"An encyclopedic memory for case law.","tags":{"Organized":3,"Analytical":3}},{"text":"The ability to read people and juries.","tags":{"Psychology":3,"Empathy":3}},{"text":"Exceptional public speaking and charisma.","tags":{"Communication":3,"Expressive":3}},{"text":"Relentless aggression and negotiation skills.","tags":{"Leadership":3,"ProblemSolving":2}}]},
        {"text":"When organizing an event, you are the person who:","options":[{"text":"Drafts the contracts with vendors to avoid liability.","tags":{"Logical":3,"Analytical":3}},{"text":"Manages the budget spreadsheet down to the penny.","tags":{"Organized":3,"Practical":2}},{"text":"Hypeman who gets everyone excited to go.","tags":{"Communication":3,"Leadership":2}},{"text":"Makes sure everyone feels included and welcome.","tags":{"Empathy":3,"Social":3}}]},
        {"text":"How do you feel about strict dress codes (like suits)?","options":[{"text":"I like them; they command respect and authority.","tags":{"Leadership":3,"Organized":2}},{"text":"I hate them; I prefer to express my individuality.","tags":{"Creative":3,"Independent":3}},{"text":"I'll wear whatever is required to win the case.","tags":{"Practical":3,"Adaptable":3}},{"text":"I find them physically uncomfortable.","tags":{"Sensitive":3}}]},
        {"text":"If you find a loophole in a school/work rule, you:","options":[{"text":"Exploit it quietly for my own benefit.","tags":{"ProblemSolving":3,"Practical":2}},{"text":"Tell management so they can fix the flaw.","tags":{"Logical":3,"Organized":2}},{"text":"Tell all my friends so we can all use it.","tags":{"Social":3,"Communication":3}},{"text":"I don't look for loopholes; I just follow the rules.","tags":{"Dedicated":3,"Easygoing":2}}]},
        {"text":"What is your approach to historical research?","options":[{"text":"Cross-referencing multiple primary sources for accuracy.","tags":{"Analytical":3,"Organized":3}},{"text":"Focusing on the stories of marginalized groups.","tags":{"Empathy":3,"Social":3}},{"text":"Studying the evolution of political power.","tags":{"Leadership":3,"Logical":2}},{"text":"Looking at the technological advancements of the era.","tags":{"Technical":3,"Practical":2}}]},
        {"text":"If you were a detective, your strongest trait would be:","options":[{"text":"Following the paper trail of money.","tags":{"Analytical":3,"Organized":3}},{"text":"Interrogating suspects and reading their body language.","tags":{"Psychology":3,"Communication":3}},{"text":"Collecting and processing physical evidence.","tags":{"Technical":3,"Practical":3}},{"text":"Never giving up on a cold case.","tags":{"Dedicated":3,"Empathy":2}}]},
        {"text":"How do you feel about the phrase 'innocent until proven guilty'?","options":[{"text":"It is the absolute bedrock of a civilized society.","tags":{"Logical":3,"Analytical":3}},{"text":"It's a nice thought, but the system is biased.","tags":{"Empathy":3,"Social":3}},{"text":"It makes it too hard to put dangerous people away.","tags":{"Practical":3,"Leadership":2}},{"text":"I think it depends entirely on the evidence presented.","tags":{"ProblemSolving":3}}]},
        {"text":"When reading a contract, what do you look for first?","options":[{"text":"The termination and exit clauses.","tags":{"Analytical":3,"ProblemSolving":3}},{"text":"The compensation and payment terms.","tags":{"Practical":3,"Logical":2}},{"text":"The liability and indemnification sections.","tags":{"Organized":3,"Logical":3}},{"text":"I just read the summary my lawyer gives me.","tags":{"Resourceful":3,"Easygoing":2}}]},
        {"text":"What is your definition of 'Justice'?","options":[{"text":"The strict and equal application of the law to everyone.","tags":{"Logical":3,"Analytical":3}},{"text":"Restoring the victim and healing the community.","tags":{"Empathy":3,"Social":3}},{"text":"Ensuring the powerful cannot exploit the weak.","tags":{"Leadership":3,"ProblemSolving":3}},{"text":"An abstract concept that depends on who has the best lawyer.","tags":{"Practical":3,"Creative":2}}]}
    ]
};

// ---------------------------------------------------------------------
// 2. RANDOM QUESTION SHUFFLER ROUTE
// ---------------------------------------------------------------------
// When a user selects a category, this route grabs the 25 questions, 
// shuffles them randomly, and returns exactly 5.
app.get('/api/questions', (req, res) => {
    const requestedInterest = req.query.interest; 
    
    // Fallback to TechAI if category is not found
    const pool = questionsDB[requestedInterest] || questionsDB["TechAI"];
    
    // Shuffle the pool randomly
    const shuffledPool = [...pool].sort(() => 0.5 - Math.random());
    
    // Slice off 5 questions for the UI
    const selectedQuestions = shuffledPool.slice(0, 5);
    
    res.json(selectedQuestions);
});

// ---------------------------------------------------------------------
// 3. AI MATCHING QUEUE ENGINE & ROUTE HANDLER
// ---------------------------------------------------------------------
const requestQueue = [];
let isProcessingQueue = false;

async function processQueue() {
    if (isProcessingQueue || requestQueue.length === 0) return;
    isProcessingQueue = true;

    // Pull the next request from the queue
    const { req, res } = requestQueue.shift();

    try {
        const { userTraits, interest, studentInput } = req.body;

        const prompt = `
            You are an expert career counselor for high school and college students. 
            A student is deeply interested in the broad category of: ${interest}.
            They completed a behavioral assessment and demonstrated these dominant traits: ${JSON.stringify(userTraits)}.
            They also provided this personal context about their goals/hobbies: "${studentInput}".
            
            Analyze their psychological traits alongside their personal context. Recommend 4 highly specific, modern career paths tailored exactly to them. 
            
            Return the output strictly as a JSON array of 4 career objects using this schema:
            [
              {
                "title": "String (Name of career)",
                "icon": "Emoji",
                "desc": "String (A short encouraging summary of why it fits them)",
                "phases": [
                  { "title": "Phase 1: Foundation", "steps": "String (Specific actionable steps)" },
                  { "title": "Phase 2: Skill Building", "steps": "String" },
                  { "title": "Phase 3: Career Entry", "steps": "String" }
                ],
                "books": ["String (Book title by Author)", "String"]
              }
            ]
        `;

        // Make API request to NVIDIA Nemotron (or fallback OpenAI model)
        const response = await ai.chat.completions.create({
            model: process.env.NEMOTRON_MODEL || 'nvidia/nemotron-3-ultra-550b-a55b:free',
            messages: [
                {
                    role: 'system',
                    content: 'You are a career counseling assistant that only responds in valid JSON arrays.'
                },
                {
                    role: 'user',
                    content: prompt
                }
            ],
            response_format: { type: "json_object" }
        });

        const rawContent = response.choices[0]?.message?.content;

        if (!rawContent) {
            return res.status(400).json({ error: "The API returned an empty response. Please try again." });
        }

        // Clean out markdown wrappers if present and parse
        const cleanJsonText = rawContent.replace(/```json|```/g, '').trim();
        let finalRoadmap = JSON.parse(cleanJsonText);

        // Extract array if wrapped in an object
        if (!Array.isArray(finalRoadmap) && typeof finalRoadmap === 'object') {
            const possibleArray = Object.values(finalRoadmap).find(val => Array.isArray(val));
            if (possibleArray) {
                finalRoadmap = possibleArray;
            }
        }
        
        res.json(finalRoadmap); 

    } catch (error) {
        console.error("AI Queue Error:", error);
        res.status(500).json({ error: "Failed to generate roadmap. The AI encountered an unexpected issue with the input." });
    } finally {
        // Cooldown ensures rate limiting and guarantees queue processing resumes even on error
        setTimeout(() => {
            isProcessingQueue = false;
            processQueue(); 
        }, 2000); 
    }
}

// Queue route endpoint
app.post('/api/calculate-result', (req, res) => {
    requestQueue.push({ req, res });
    processQueue();
});

// Start the server
app.listen(PORT, () => console.log(`AI Matching Engine alive on Port ${PORT}`));