require('dotenv').config(); // Loads your .env file
const express = require('express');
const cors = require('cors');
const path = require('path');
const { GoogleGenAI } = require('@google/genai'); // Import the Gemini SDK

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// Initialize Gemini 
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

// 1. MASSIVE STATIC QUESTION POOL (150 Questions)
const questionsDB = {
    "TechAI": [
        {"text":"When your computer freezes, what is your first reaction?","options":[{"text":"Troubleshoot and fix it myself.","tags":{"Technical":3,"ProblemSolving":2}},{"text":"Search Google/YouTube for a fix.","tags":{"Analytical":2,"Resourceful":3}},{"text":"Ask a friend who is good with tech.","tags":{"Communication":2}},{"text":"Restart it and hope for the best.","tags":{"Easygoing":1}}]},
        {"text":"What do you notice first about a new app?","options":[{"text":"How fast and smooth it runs.","tags":{"Technical":3}},{"text":"How cool the layout looks.","tags":{"Creative":3}},{"text":"How easy it is to understand.","tags":{"Empathy":2}},{"text":"The privacy settings.","tags":{"Analytical":3}}]},
        {"text":"Which part of building a website sounds most fun?","options":[{"text":"Writing the backend code.","tags":{"Technical":3,"Analytical":2}},{"text":"Designing the logo and colors.","tags":{"Creative":3}},{"text":"Writing the text and articles.","tags":{"Communication":3}},{"text":"Planning how pages link together.","tags":{"Organized":3}}]},
        {"text":"How do you prefer to learn something new?","options":[{"text":"Taking it apart to see how it works.","tags":{"Analytical":3,"Technical":2}},{"text":"Watching a visual tutorial.","tags":{"Creative":2}},{"text":"Reading the official manual.","tags":{"Organized":2}},{"text":"Practicing with a group.","tags":{"Communication":3}}]},
        {"text":"What type of puzzles do you enjoy most?","options":[{"text":"Logic/math puzzles (Sudoku).","tags":{"Analytical":3,"ProblemSolving":2}},{"text":"Word puzzles (Crosswords).","tags":{"Communication":2}},{"text":"Visual puzzles (Jigsaw).","tags":{"Creative":2}},{"text":"Real-world challenges.","tags":{"Practical":3}}]},
        {"text":"When learning a complex idea, you:","options":[{"text":"Ask about the specific mechanics.","tags":{"Analytical":3}},{"text":"Imagine it visually.","tags":{"Creative":2}},{"text":"Relate it to people.","tags":{"Empathy":3}},{"text":"Write bullet points.","tags":{"Organized":3}}]},
        {"text":"Your perfect work environment is:","options":[{"text":"Quiet room with dual monitors.","tags":{"Technical":3,"Independent":2}},{"text":"Lively office sharing ideas.","tags":{"Communication":3,"Creative":1}},{"text":"A highly organized desk.","tags":{"Organized":3}},{"text":"Flexible space to move around.","tags":{"Adaptable":3}}]},
        {"text":"If you had to read a book right now, it would be:","options":[{"text":"Sci-fi or future technology.","tags":{"Imaginative":3,"Technical":2}},{"text":"A biography of a leader.","tags":{"Leadership":3}},{"text":"A mystery novel.","tags":{"Analytical":3}},{"text":"A how-to guide.","tags":{"Practical":3}}]},
        {"text":"What excites you most about AI?","options":[{"text":"How it processes massive data.","tags":{"Analytical":3}},{"text":"How it can generate art/music.","tags":{"Creative":3}},{"text":"How it can help people in daily life.","tags":{"Empathy":3}},{"text":"How it automates boring tasks.","tags":{"Logical":3}}]},
        {"text":"You find a bug in a video game. You:","options":[{"text":"Try to replicate it to see why it happens.","tags":{"Analytical":3,"ProblemSolving":2}},{"text":"Use it to your advantage to win.","tags":{"Logical":3}},{"text":"Report it to the developers.","tags":{"Organized":2}},{"text":"Ignore it and keep playing.","tags":{"Easygoing":2}}]},
        {"text":"What is your favorite subject in school?","options":[{"text":"Computer Science / IT.","tags":{"Technical":3}},{"text":"Math / Physics.","tags":{"Analytical":3}},{"text":"Art / Graphic Design.","tags":{"Creative":3}},{"text":"History / English.","tags":{"Communication":2}}]},
        {"text":"How do you handle a messy folder of files?","options":[{"text":"Write a script to organize them.","tags":{"Technical":3,"ProblemSolving":3}},{"text":"Manually sort into perfect folders.","tags":{"Organized":3}},{"text":"Only search for what I need.","tags":{"Practical":2}},{"text":"Leave it messy, I know where things are.","tags":{"Adaptable":2}}]},
        {"text":"If you could invent one thing, it would be:","options":[{"text":"A new coding language.","tags":{"Technical":3,"Analytical":2}},{"text":"A robot that cleans the house.","tags":{"Practical":3}},{"text":"A new musical instrument.","tags":{"Creative":3}},{"text":"An app to connect lonely people.","tags":{"Empathy":3}}]},
        {"text":"When buying a laptop, you look for:","options":[{"text":"RAM, Processor speed, and OS.","tags":{"Technical":3}},{"text":"Screen resolution and color accuracy.","tags":{"Creative":3}},{"text":"The cheapest one that works.","tags":{"Practical":3}},{"text":"The one all my friends have.","tags":{"Social":2}}]},
        {"text":"How do you feel about coding?","options":[{"text":"I love the logic and problem solving.","tags":{"Technical":3,"Analytical":3}},{"text":"It's a useful tool to build my designs.","tags":{"Creative":2,"Practical":2}},{"text":"It seems boring and too complex.","tags":{"Social":2}},{"text":"I prefer dealing with hardware over software.","tags":{"Technical":2}}]},
        {"text":"When a group project requires a presentation, you:","options":[{"text":"Format the slides to look perfect.","tags":{"Creative":3}},{"text":"Organize the data and research.","tags":{"Analytical":3}},{"text":"Do the actual speaking.","tags":{"Communication":3}},{"text":"Manage the timeline.","tags":{"Organized":3}}]},
        {"text":"What is your approach to password security?","options":[{"text":"Use a password manager with complex hashes.","tags":{"Technical":3,"Organized":2}},{"text":"Use a memorable phrase with numbers.","tags":{"Practical":3}},{"text":"Use the same password for everything.","tags":{"Easygoing":1}},{"text":"Write them down in a physical notebook.","tags":{"Organized":2}}]},
        {"text":"If you could master any skill instantly, it would be:","options":[{"text":"Hacking/Cybersecurity.","tags":{"Technical":3,"Analytical":2}},{"text":"Digital Animation.","tags":{"Creative":3}},{"text":"Public Speaking.","tags":{"Communication":3}},{"text":"Advanced Mathematics.","tags":{"Logical":3}}]},
        {"text":"How do you stay updated on news?","options":[{"text":"Tech blogs and forums like Reddit.","tags":{"Technical":3}},{"text":"Social media feeds.","tags":{"Social":3}},{"text":"Traditional news websites.","tags":{"Organized":2}},{"text":"I don't really follow the news.","tags":{"Independent":2}}]},
        {"text":"When setting up a smart home device, you:","options":[{"text":"Integrate it perfectly with my network.","tags":{"Technical":3}},{"text":"Just want it to play music and turn on lights.","tags":{"Practical":3}},{"text":"Worry about it recording my data.","tags":{"Analytical":3}},{"text":"Make it change colors based on my mood.","tags":{"Creative":3}}]},
        {"text":"Which of these sounds most tedious to you?","options":[{"text":"Writing documentation for code.","tags":{"Technical":1,"Creative":3}},{"text":"Debugging a small syntax error.","tags":{"Logical":2}},{"text":"Drawing the same frame 100 times.","tags":{"Analytical":3}},{"text":"Talking to angry customers.","tags":{"Independent":3}}]},
        {"text":"How do you explain Wi-Fi to a child?","options":[{"text":"'Invisible waves that carry internet.'","tags":{"Communication":3,"Creative":2}},{"text":"'Radio frequencies transmitting data.'","tags":{"Technical":3}},{"text":"'Magic that makes YouTube work.'","tags":{"Empathy":2}},{"text":"I wouldn't know how to simplify it.","tags":{"Analytical":2}}]},
        {"text":"What is your favorite part of a video game?","options":[{"text":"The core gameplay mechanics and loops.","tags":{"Analytical":3}},{"text":"The graphics and soundtrack.","tags":{"Creative":3}},{"text":"The storyline and character dialogue.","tags":{"Empathy":2}},{"text":"Playing with my friends online.","tags":{"Social":3}}]},
        {"text":"If you ran a tech company, you would be the:","options":[{"text":"Lead Developer writing the best code.","tags":{"Technical":3}},{"text":"CEO pitching the vision to investors.","tags":{"Leadership":3}},{"text":"Lead Designer making the UI beautiful.","tags":{"Creative":3}},{"text":"Project Manager keeping everyone on track.","tags":{"Organized":3}}]},
        {"text":"How do you feel about open-source software?","options":[{"text":"Love it, I want to contribute to the code.","tags":{"Technical":3,"Collaborative":2}},{"text":"It's great because it's free.","tags":{"Practical":3}},{"text":"I prefer polished, paid software.","tags":{"Organized":2}},{"text":"I don't know what that means.","tags":{"Easygoing":1}}]}
    ],
    "LawAdmin": [
        {"text":"Two friends are arguing. You:","options":[{"text":"Listen to both and find a compromise.","tags":{"Leadership":3,"ProblemSolving":2}},{"text":"Use facts to see who is right.","tags":{"Analytical":3,"Logical":2}},{"text":"Stay out of it.","tags":{"Independent":2}},{"text":"Make a joke to ease tension.","tags":{"Empathy":2,"Communication":2}}]},
        {"text":"When planning a group trip, you:","options":[{"text":"Create the detailed schedule.","tags":{"Organized":3,"Leadership":2}},{"text":"Research the fun places.","tags":{"Analytical":2,"Creative":1}},{"text":"Ensure everyone is happy.","tags":{"Empathy":3}},{"text":"Just go with the flow.","tags":{"Adaptable":3}}]},
        {"text":"How do you feel about rules?","options":[{"text":"Essential and must be followed.","tags":{"Organized":3,"Logical":2}},{"text":"Good, but can be bent if fair.","tags":{"Analytical":2,"Empathy":2}},{"text":"I like finding loopholes.","tags":{"ProblemSolving":3,"Analytical":2}},{"text":"Restrictive, I prefer freedom.","tags":{"Creative":3}}]},
        {"text":"Giving a presentation makes you feel:","options":[{"text":"Confident. I like persuading people.","tags":{"Leadership":3,"Communication":3}},{"text":"Nervous, but I rely on notes.","tags":{"Organized":3}},{"text":"I let my group talk instead.","tags":{"Independent":2}},{"text":"I try to make it entertaining.","tags":{"Creative":2}}]},
        {"text":"You find an error in a document:","options":[{"text":"Point it out and correct it.","tags":{"Analytical":3,"Organized":2}},{"text":"Ignore it if the point is clear.","tags":{"Adaptable":2}},{"text":"Use it to negotiate a better deal.","tags":{"ProblemSolving":3,"Leadership":2}},{"text":"Quietly fix it to save embarrassment.","tags":{"Empathy":3}}]},
        {"text":"What do you value most in a leader?","options":[{"text":"Fairness and justice.","tags":{"Logical":3}},{"text":"Organizing chaos into order.","tags":{"Organized":3}},{"text":"Charisma and inspiration.","tags":{"Leadership":3,"Communication":2}},{"text":"Caring about the team.","tags":{"Empathy":3}}]},
        {"text":"Dealing with a pile of paperwork:","options":[{"text":"Sort it and tackle it methodically.","tags":{"Organized":3,"Analytical":2}},{"text":"Rush the easy parts first.","tags":{"ProblemSolving":2}},{"text":"Do it together with friends.","tags":{"Communication":2}},{"text":"Find a way to automate it.","tags":{"Technical":2}}]},
        {"text":"If you were on a debate team, your role is:","options":[{"text":"The closer who delivers the final emotional pitch.","tags":{"Communication":3,"Leadership":2}},{"text":"The researcher digging up cold hard facts.","tags":{"Analytical":3,"Organized":2}},{"text":"The strategist finding flaws in the opponent's logic.","tags":{"Logical":3,"ProblemSolving":2}},{"text":"I would hate being on a debate team.","tags":{"Creative":2}}]},
        {"text":"How do you react to sudden changes in plans?","options":[{"text":"I get frustrated, I like my schedule.","tags":{"Organized":3}},{"text":"I quickly draft a new plan.","tags":{"Analytical":2,"Adaptable":2}},{"text":"I see it as an exciting new adventure.","tags":{"Creative":3}},{"text":"I check how the rest of the group feels about it.","tags":{"Empathy":3}}]},
        {"text":"When signing a contract (like terms of service), you:","options":[{"text":"Skim for the most important legal clauses.","tags":{"Analytical":3,"Logical":2}},{"text":"Read every single word carefully.","tags":{"Organized":3}},{"text":"Scroll to the bottom and click accept.","tags":{"Practical":3}},{"text":"Ask someone else if it's safe to sign.","tags":{"Communication":2}}]},
        {"text":"What would be your ideal business to start?","options":[{"text":"A highly profitable consulting firm.","tags":{"Leadership":3,"Logical":2}},{"text":"A non-profit helping the local community.","tags":{"Empathy":3,"Social":3}},{"text":"A creative marketing and design agency.","tags":{"Creative":3}},{"text":"A tech startup building a new app.","tags":{"Technical":3}}]},
        {"text":"When delegating tasks in a team, you:","options":[{"text":"Assign based on everyone's specific strengths.","tags":{"Leadership":3,"Analytical":2}},{"text":"Take the hardest parts for yourself.","tags":{"Dedicated":3}},{"text":"Let people pick what they want to do.","tags":{"Empathy":2,"Adaptable":2}},{"text":"Create a detailed spreadsheet of duties.","tags":{"Organized":3}}]},
        {"text":"How do you win an argument?","options":[{"text":"By presenting undeniable statistics and evidence.","tags":{"Logical":3,"Analytical":3}},{"text":"By appealing to their emotions and morals.","tags":{"Communication":3,"Empathy":2}},{"text":"By wearing them down until they give up.","tags":{"Dedicated":2}},{"text":"I avoid arguments entirely.","tags":{"Easygoing":3}}]},
        {"text":"In a courtroom, which role appeals to you most?","options":[{"text":"The Judge, making the final fair decision.","tags":{"Leadership":3,"Logical":3}},{"text":"The Lawyer, cross-examining witnesses.","tags":{"Communication":3,"Analytical":2}},{"text":"The Detective, finding the hidden clues.","tags":{"ProblemSolving":3,"Technical":1}},{"text":"The Jury, listening and deciding together.","tags":{"Social":2,"Empathy":2}}]},
        {"text":"What is the best way to handle a difficult customer?","options":[{"text":"Stay calm, quote the store policy, and don't budge.","tags":{"Organized":3,"Logical":2}},{"text":"Listen actively and offer a refund to make them happy.","tags":{"Empathy":3,"Communication":2}},{"text":"Call the manager to deal with it.","tags":{"Practical":3}},{"text":"Find a creative compromise that saves the company money.","tags":{"ProblemSolving":3}}]},
        {"text":"If you were given a $10,000 budget for a project, you would:","options":[{"text":"Track every penny in an Excel spreadsheet.","tags":{"Organized":3,"Analytical":2}},{"text":"Invest it strategically to try and make more.","tags":{"Logical":3,"Leadership":2}},{"text":"Spend it on making the project look incredible.","tags":{"Creative":3}},{"text":"Split it evenly among the team members.","tags":{"Empathy":3}}]},
        {"text":"When someone breaks a minor rule, you:","options":[{"text":"Report them; rules exist for a reason.","tags":{"Organized":3,"Logical":3}},{"text":"Warn them so they don't get caught next time.","tags":{"Empathy":2}},{"text":"Ignore it as long as nobody got hurt.","tags":{"Adaptable":3}},{"text":"Use it as leverage later.","tags":{"ProblemSolving":2}}]},
        {"text":"What motivates you to work hard?","options":[{"text":"Getting a promotion or a leadership title.","tags":{"Leadership":3}},{"text":"Earning a high salary.","tags":{"Practical":3}},{"text":"Knowing I did a flawless, perfect job.","tags":{"Organized":3}},{"text":"Helping people who need it.","tags":{"Empathy":3}}]},
        {"text":"How do you handle keeping secrets?","options":[{"text":"I am a vault. I never tell anyone.","tags":{"Logical":3,"Dedicated":2}},{"text":"I keep it, unless it harms someone else.","tags":{"Empathy":3,"Analytical":2}},{"text":"I usually end up gossiping about it.","tags":{"Communication":3}},{"text":"I forget the secret within an hour anyway.","tags":{"Easygoing":3}}]},
        {"text":"Your preferred method of communication in business is:","options":[{"text":"A formally formatted, concise email.","tags":{"Organized":3,"Logical":2}},{"text":"A quick phone call to hash it out.","tags":{"Communication":3}},{"text":"A face-to-face meeting over coffee.","tags":{"Social":3,"Empathy":2}},{"text":"Instant messaging (Slack/Teams).","tags":{"Technical":2,"Adaptable":2}}]},
        {"text":"If you witness a crime, you would:","options":[{"text":"Memorize the suspect's description and call 911.","tags":{"Analytical":3,"Organized":2}},{"text":"Rush in to try and stop it.","tags":{"Leadership":3,"Dedicated":2}},{"text":"Check to see if the victim is okay first.","tags":{"Empathy":3}},{"text":"Record it on your phone for evidence.","tags":{"Technical":2,"Practical":2}}]},
        {"text":"When negotiating a salary, you:","options":[{"text":"Research market averages and demand your worth.","tags":{"Analytical":3,"Logical":3}},{"text":"Charm the interviewer into offering more.","tags":{"Communication":3}},{"text":"Accept the first offer because negotiating is scary.","tags":{"Reserved":3}},{"text":"Ask for extra vacation days instead of money.","tags":{"Creative":2,"Practical":2}}]},
        {"text":"How do you manage your personal finances?","options":[{"text":"Strict budget, saving a specific percentage monthly.","tags":{"Organized":3,"Analytical":2}},{"text":"I check my balance before buying big things.","tags":{"Practical":3}},{"text":"I spend what I want and hope for the best.","tags":{"Easygoing":3}},{"text":"I invest heavily in stocks and crypto.","tags":{"Logical":3,"ProblemSolving":2}}]},
        {"text":"What kind of documentaries do you watch?","options":[{"text":"True crime and legal investigations.","tags":{"Analytical":3,"Logical":2}},{"text":"Nature and the environment.","tags":{"Nature":3}},{"text":"Historical biographies of powerful people.","tags":{"Leadership":3}},{"text":"Art, music, or pop culture.","tags":{"Creative":3}}]},
        {"text":"In a corporate meeting, you are the one who:","options":[{"text":"Takes the minutes and schedules the next steps.","tags":{"Organized":3}},{"text":"Challenges the ideas being presented.","tags":{"Analytical":3,"Logical":2}},{"text":"Pitches the big, bold ideas.","tags":{"Creative":3,"Leadership":2}},{"text":"Tries to keep the meeting under 30 minutes.","tags":{"Practical":3}}]}
    ],
    "ArtsDesign": [
        {"text":"In a coffee shop, you notice first:","options":[{"text":"Furniture, lighting, and wall art.","tags":{"Creative":3,"Visual":3}},{"text":"The background music.","tags":{"Creative":2,"Auditory":3}},{"text":"How fast the line moves.","tags":{"Analytical":2,"Organized":2}},{"text":"The vibe of the people.","tags":{"Empathy":3}}]},
        {"text":"Bored in class, you are likely:","options":[{"text":"Doodling in the margins.","tags":{"Creative":3,"Visual":2}},{"text":"Writing a story or poem.","tags":{"Creative":2,"Communication":3}},{"text":"Daydreaming big ideas.","tags":{"Imaginative":3}},{"text":"Reading ahead.","tags":{"Analytical":3}}]},
        {"text":"Deciding what clothes to wear:","options":[{"text":"Mixing colors and styles.","tags":{"Creative":3,"Expressive":3}},{"text":"Whatever is comfortable.","tags":{"Practical":3}},{"text":"Following current trends.","tags":{"Social":2}},{"text":"Grabbing the first clean thing.","tags":{"Easygoing":2}}]},
        {"text":"When buying a product, you choose based on:","options":[{"text":"Beautiful packaging and design.","tags":{"Creative":3}},{"text":"Best features and specs.","tags":{"Analytical":3,"Technical":2}},{"text":"The cheapest option.","tags":{"Practical":3}},{"text":"Friend recommendations.","tags":{"Communication":2}}]},
        {"text":"Favorite way to express feelings:","options":[{"text":"Drawing, painting, or designing.","tags":{"Creative":3}},{"text":"Writing or talking.","tags":{"Communication":3}},{"text":"Music or acting.","tags":{"Expressive":3}},{"text":"Processing quietly alone.","tags":{"Independent":2}}]},
        {"text":"Which software to master?","options":[{"text":"Adobe Photoshop/Illustrator.","tags":{"Creative":3,"Technical":2}},{"text":"Microsoft Excel.","tags":{"Analytical":3,"Organized":2}},{"text":"Video editing (Premiere).","tags":{"Creative":2,"Technical":2}},{"text":"I don't like complex software.","tags":{"Practical":2}}]},
        {"text":"On a blank billboard, you put:","options":[{"text":"Original artwork.","tags":{"Creative":3}},{"text":"A clever, funny quote.","tags":{"Communication":3,"Empathy":2}},{"text":"A business ad.","tags":{"Logical":2,"Leadership":2}},{"text":"A confusing puzzle.","tags":{"Analytical":3}}]},
        {"text":"When you take a photo, what is most important?","options":[{"text":"The composition and lighting.","tags":{"Creative":3,"Visual":3}},{"text":"Capturing a genuine emotion.","tags":{"Empathy":3,"Expressive":2}},{"text":"Making sure everyone is in frame.","tags":{"Organized":2}},{"text":"I prefer taking videos over photos.","tags":{"Technical":2}}]},
        {"text":"How do you feel about museums?","options":[{"text":"I could spend all day looking at the details of art.","tags":{"Creative":3,"Visual":2}},{"text":"I like the history and reading the plaques.","tags":{"Analytical":3}},{"text":"I prefer interactive science museums.","tags":{"Technical":3}},{"text":"I get bored quickly.","tags":{"Practical":2}}]},
        {"text":"If you redesign your bedroom, you start with:","options":[{"text":"Picking a specific color palette and theme.","tags":{"Creative":3,"Organized":2}},{"text":"Moving furniture for better space and flow.","tags":{"Analytical":2,"Practical":3}},{"text":"Hanging up posters of things I love.","tags":{"Expressive":3}},{"text":"I don't care what my room looks like.","tags":{"Easygoing":3}}]},
        {"text":"What kind of YouTube videos do you binge?","options":[{"text":"Video essays on movies, art, or game design.","tags":{"Analytical":2,"Creative":3}},{"text":"Vlogs and lifestyle content.","tags":{"Social":3}},{"text":"Tech reviews and unboxings.","tags":{"Technical":3}},{"text":"Comedy and sketch shows.","tags":{"Communication":2,"Expressive":2}}]},
        {"text":"When listening to a song, what grabs you first?","options":[{"text":"The lyrics and their meaning.","tags":{"Communication":3,"Empathy":2}},{"text":"The beat and the instrumental production.","tags":{"Creative":3,"Auditory":3}},{"text":"The technical skill of the musicians.","tags":{"Analytical":2,"Technical":2}},{"text":"I just want something to dance to.","tags":{"Expressive":3}}]},
        {"text":"If you were a character in a movie, you'd be:","options":[{"text":"The visionary director behind the camera.","tags":{"Leadership":2,"Creative":3}},{"text":"The charismatic lead actor.","tags":{"Expressive":3,"Communication":3}},{"text":"The writer who created the whole universe.","tags":{"Imaginative":3}},{"text":"The brilliant hacker sidekick.","tags":{"Technical":3}}]},
        {"text":"How do you feel about modern abstract art?","options":[{"text":"I love interpreting the hidden meanings.","tags":{"Creative":3,"Analytical":2}},{"text":"I appreciate the colors, even if it's weird.","tags":{"Visual":3}},{"text":"I think it's mostly a scam. Anyone could paint that.","tags":{"Logical":3,"Practical":2}},{"text":"It's okay, but I prefer realistic drawings.","tags":{"Organized":2}}]},
        {"text":"When writing an essay, you spend the most time:","options":[{"text":"Finding the perfect descriptive words.","tags":{"Communication":3,"Creative":2}},{"text":"Making sure the formatting and citations are flawless.","tags":{"Organized":3}},{"text":"Structuring a bulletproof argument.","tags":{"Analytical":3,"Logical":2}},{"text":"Procrastinating until the night before.","tags":{"Adaptable":2}}]},
        {"text":"What is your relationship with social media?","options":[{"text":"I carefully curate my grid to look aesthetic.","tags":{"Creative":3,"Visual":3}},{"text":"I use it to chat and stay connected.","tags":{"Social":3,"Communication":2}},{"text":"I mainly lurk and consume information.","tags":{"Analytical":2}},{"text":"I rarely use it. I prefer real life.","tags":{"Independent":3}}]},
        {"text":"If you had to learn an instrument, it would be:","options":[{"text":"Piano (complex and versatile).","tags":{"Analytical":3,"Creative":2}},{"text":"Electric Guitar (loud and expressive).","tags":{"Expressive":3}},{"text":"Drums (rhythm and energy).","tags":{"Practical":3}},{"text":"Synthesizer (electronic and technical).","tags":{"Technical":3}}]},
        {"text":"How do you sketch or draw?","options":[{"text":"Freehand, letting my imagination guide me.","tags":{"Creative":3,"Imaginative":3}},{"text":"With a ruler, measuring perfect perspective.","tags":{"Organized":3,"Analytical":2}},{"text":"I can only draw stick figures.","tags":{"Practical":2}},{"text":"I trace or copy things I see.","tags":{"Visual":2}}]},
        {"text":"When watching an animated movie, you think about:","options":[{"text":"How many hours it took to render the lighting.","tags":{"Technical":3,"Creative":2}},{"text":"The character design and color choices.","tags":{"Creative":3,"Visual":3}},{"text":"The vocal performances of the actors.","tags":{"Expressive":3}},{"text":"Just enjoying the plot.","tags":{"Easygoing":3}}]},
        {"text":"Your favorite way to tell a story is:","options":[{"text":"A graphic novel or comic book.","tags":{"Creative":3,"Visual":3}},{"text":"A well-written short story.","tags":{"Communication":3}},{"text":"A short video or TikTok.","tags":{"Technical":2,"Expressive":2}},{"text":"Telling it out loud with lots of hand gestures.","tags":{"Communication":3,"Expressive":3}}]},
        {"text":"How do you feel about tattoos?","options":[{"text":"Love them, they are permanent body art.","tags":{"Creative":3,"Expressive":3}},{"text":"I'd only get one if it had a deep, hidden meaning.","tags":{"Analytical":2,"Imaginative":2}},{"text":"I don't like them, I prefer a clean look.","tags":{"Organized":2}},{"text":"Too expensive and painful.","tags":{"Practical":3}}]},
        {"text":"What would you do at a music festival?","options":[{"text":"Be in the front row, singing every word.","tags":{"Expressive":3,"Social":3}},{"text":"Sit in the back, admiring the stage lighting and sound design.","tags":{"Technical":3,"Creative":2}},{"text":"Wander around looking at the art installations and food.","tags":{"Imaginative":3}},{"text":"Complain about the crowds and noise.","tags":{"Independent":2}}]},
        {"text":"If you write a blog, what is it about?","options":[{"text":"Fashion, design, or architecture trends.","tags":{"Creative":3,"Visual":3}},{"text":"Personal poetry and life reflections.","tags":{"Communication":3,"Empathy":2}},{"text":"Tech reviews and coding tutorials.","tags":{"Technical":3}},{"text":"Politics and cultural commentary.","tags":{"Analytical":3,"Logical":2}}]},
        {"text":"How important is handwriting to you?","options":[{"text":"Very, I practice calligraphy and love nice pens.","tags":{"Creative":3,"Organized":2}},{"text":"I type everything, so it doesn't matter.","tags":{"Technical":3,"Practical":2}},{"text":"Mine is messy but it gets the job done.","tags":{"Adaptable":2}},{"text":"I only care if it's readable.","tags":{"Logical":2}}]},
        {"text":"When you see a bad advertisement, you think:","options":[{"text":"'I could have designed a much better graphic.'","tags":{"Creative":3,"Visual":3}},{"text":"'The copywriting on this makes no sense.'","tags":{"Communication":3,"Analytical":2}},{"text":"'This is a waste of a marketing budget.'","tags":{"Logical":3,"Leadership":2}},{"text":"'I wonder how much they paid for this.'","tags":{"Practical":3}}]}
    ],
    "Health": [
        {"text":"A friend is bleeding. You:","options":[{"text":"Stay calm, clean and bandage it.","tags":{"Practical":3,"ProblemSolving":2}},{"text":"Comfort them so they aren't scared.","tags":{"Empathy":3}},{"text":"Faint or look away.","tags":{"Sensitive":3}},{"text":"Call someone who knows what to do.","tags":{"Communication":2}}]},
        {"text":"How do you feel about daily routines?","options":[{"text":"Love having a strict schedule.","tags":{"Organized":3}},{"text":"Like them, but need flexibility.","tags":{"Adaptable":2}},{"text":"Thrive when every day is different.","tags":{"Adaptable":3,"ProblemSolving":2}},{"text":"Hate routines, prefer to wing it.","tags":{"Creative":2}}]},
        {"text":"When a friend has a problem, you:","options":[{"text":"Listen quietly and offer a shoulder.","tags":{"Empathy":3}},{"text":"Offer solutions to fix it.","tags":{"ProblemSolving":3,"Logical":2}},{"text":"Try to distract them with fun.","tags":{"Creative":2,"Social":2}},{"text":"Help them analyze why it happened.","tags":{"Analytical":3}}]},
        {"text":"Working under extreme pressure:","options":[{"text":"I stay highly focused and act quickly.","tags":{"ProblemSolving":3,"Leadership":2}},{"text":"I get anxious but push through.","tags":{"Dedicated":3}},{"text":"I need to step back and breathe.","tags":{"Analytical":2}},{"text":"I prefer low-stress environments.","tags":{"Creative":2}}]},
        {"text":"In biology class, the human body is:","options":[{"text":"Fascinating! I want to know how organs work.","tags":{"Analytical":3,"Technical":2}},{"text":"Interesting, but too much memory work.","tags":{"Practical":2}},{"text":"Gross. I prefer plants/animals.","tags":{"Nature":3}},{"text":"Only cared about nutrition/fitness.","tags":{"Practical":3}}]},
        {"text":"Comfortable talking to strangers?","options":[{"text":"Yes, I love making people feel heard.","tags":{"Empathy":3,"Communication":3}},{"text":"Only if I have a reason to.","tags":{"Logical":2,"Practical":2}},{"text":"Can do it, but it drains me.","tags":{"Independent":2}},{"text":"No, I am very shy.","tags":{"Reserved":2}}]},
        {"text":"Working long, unusual shifts (like nights)?","options":[{"text":"Can do it if it means helping people.","tags":{"Dedicated":3,"Empathy":2}},{"text":"Love the quiet focus of night.","tags":{"Independent":3}},{"text":"Strongly prefer a 9-to-5.","tags":{"Organized":3}},{"text":"Will do whatever pays most.","tags":{"Logical":3}}]},
        {"text":"If you see a stray animal on the street, you:","options":[{"text":"Try to catch it and take it to a vet/shelter.","tags":{"Empathy":3,"Nature":3}},{"text":"Call animal control to handle it safely.","tags":{"Organized":2,"Logical":2}},{"text":"Feel sad but keep walking.","tags":{"Sensitive":2}},{"text":"Try to feed it from a distance.","tags":{"Practical":2}}]},
        {"text":"How do you react to bad smells or gross sights?","options":[{"text":"I have a strong stomach, it doesn't bother me.","tags":{"Practical":3,"Dedicated":2}},{"text":"I gag immediately. I can't handle it.","tags":{"Sensitive":3}},{"text":"I hold my breath and get the job done.","tags":{"Adaptable":3}},{"text":"I put on a mask and gloves to investigate.","tags":{"Analytical":3,"Technical":2}}]},
        {"text":"What is your approach to eating healthy?","options":[{"text":"I track my macros and calories in an app.","tags":{"Analytical":3,"Organized":3}},{"text":"I eat intuitively based on how my body feels.","tags":{"Empathy":2,"Adaptable":2}},{"text":"I love cooking fresh, organic meals from scratch.","tags":{"Creative":3,"Nature":2}},{"text":"I eat whatever tastes good and is cheap.","tags":{"Practical":3}}]},
        {"text":"When someone is grieving, the best thing to do is:","options":[{"text":"Sit with them in silence and hold their hand.","tags":{"Empathy":3,"Emotional":3}},{"text":"Cook them meals and clean their house.","tags":{"Practical":3,"Dedicated":2}},{"text":"Give them space to process it alone.","tags":{"Independent":2}},{"text":"Recommend a good therapist.","tags":{"Analytical":2,"Logical":2}}]},
        {"text":"How is your memory for small details?","options":[{"text":"Excellent, I remember allergies and birthdays.","tags":{"Empathy":3,"Organized":3}},{"text":"Good for facts and numbers, bad for names.","tags":{"Analytical":3}},{"text":"Terrible, I have to write everything down.","tags":{"Adaptable":2}},{"text":"I only remember things I find interesting.","tags":{"Creative":2}}]},
        {"text":"You have to give someone bad news. You:","options":[{"text":"Deliver it gently and stay to comfort them.","tags":{"Empathy":3,"Communication":3}},{"text":"Rip the bandage off and tell them directly.","tags":{"Logical":3,"Practical":2}},{"text":"Try to have someone else do it.","tags":{"Reserved":2}},{"text":"Sugarcoat it so they don't panic.","tags":{"Creative":2}}]},
        {"text":"How do you feel about physical fitness?","options":[{"text":"I love pushing my body to its absolute limits.","tags":{"Dedicated":3,"Practical":2}},{"text":"I enjoy yoga and stretching for mental clarity.","tags":{"Empathy":2,"Nature":2}},{"text":"I analyze fitness science and optimize workouts.","tags":{"Analytical":3,"Technical":2}},{"text":"I hate sweating.","tags":{"Easygoing":3}}]},
        {"text":"If a child is throwing a tantrum in public, you think:","options":[{"text":"'That poor parent must be so stressed.'","tags":{"Empathy":3}},{"text":"'I wonder what triggered the child's behavior.'","tags":{"Analytical":3,"Psychology":3}},{"text":"'Someone needs to discipline that kid.'","tags":{"Logical":2}},{"text":"'I need to get out of this store right now.'","tags":{"Independent":3}}]},
        {"text":"Your favorite type of science is:","options":[{"text":"Anatomy and Physiology.","tags":{"Analytical":3,"Technical":2}},{"text":"Psychology and brain behavior.","tags":{"Empathy":3,"Analytical":2}},{"text":"Chemistry and pharmaceuticals.","tags":{"Logical":3}},{"text":"Botany and environmental science.","tags":{"Nature":3}}]},
        {"text":"How do you handle sleep deprivation?","options":[{"text":"I can push through it with coffee and adrenaline.","tags":{"Dedicated":3,"Adaptable":2}},{"text":"I become very cranky and useless.","tags":{"Sensitive":3}},{"text":"I refuse to get less than 8 hours, it's unhealthy.","tags":{"Organized":3,"Logical":2}},{"text":"I take strategic power naps.","tags":{"Analytical":3}}]},
        {"text":"If you were in a hospital, you'd want to be the:","options":[{"text":"Surgeon performing complex procedures.","tags":{"Technical":3,"ProblemSolving":3}},{"text":"Nurse holding hands and giving care.","tags":{"Empathy":3,"Dedicated":3}},{"text":"Lab tech running blood tests behind the scenes.","tags":{"Analytical":3,"Independent":2}},{"text":"Administrator organizing the beds and schedules.","tags":{"Organized":3,"Leadership":2}}]},
        {"text":"What is your view on mental health?","options":[{"text":"It is just as important as physical health.","tags":{"Empathy":3,"Logical":2}},{"text":"It can be solved by changing chemical imbalances.","tags":{"Analytical":3,"Technical":2}},{"text":"Nature and meditation are the best cures.","tags":{"Nature":3}},{"text":"People just need to toughen up.","tags":{"Practical":2,"Logical":1}}]},
        {"text":"How do you react when you get sick?","options":[{"text":"I research my symptoms extensively online.","tags":{"Analytical":3}},{"text":"I follow the doctor's orders perfectly.","tags":{"Organized":3}},{"text":"I drink tea, sleep, and use natural remedies.","tags":{"Nature":3,"Practical":2}},{"text":"I ignore it and keep going to work.","tags":{"Dedicated":3}}]},
        {"text":"When learning a physical task (like giving CPR), you:","options":[{"text":"Practice repeatedly on a dummy until perfect.","tags":{"Dedicated":3,"Practical":3}},{"text":"Memorize the textbook steps first.","tags":{"Analytical":3,"Organized":2}},{"text":"Ask the instructor to watch and correct my form.","tags":{"Communication":3}},{"text":"Hope I never actually have to use it.","tags":{"Sensitive":2}}]},
        {"text":"What do you think of alternative medicine (like acupuncture)?","options":[{"text":"If it makes the patient feel better, it's good.","tags":{"Empathy":3,"OpenMinded":3}},{"text":"It's a scam without peer-reviewed scientific proof.","tags":{"Logical":3,"Analytical":3}},{"text":"I want to learn how to do it.","tags":{"Creative":2,"Practical":2}},{"text":"I'm scared of needles.","tags":{"Sensitive":2}}]},
        {"text":"How good are you at multitasking in a chaotic room?","options":[{"text":"Excellent, I thrive when 5 things happen at once.","tags":{"Adaptable":3,"ProblemSolving":3}},{"text":"I can do it, but I make checklists to stay sane.","tags":{"Organized":3}},{"text":"Terrible. I need quiet to focus on one patient.","tags":{"Analytical":2,"Sensitive":2}},{"text":"I delegate the tasks to other people.","tags":{"Leadership":3}}]},
        {"text":"If you were a therapist, your style would be:","options":[{"text":"Listening deeply and validating their feelings.","tags":{"Empathy":3,"Communication":3}},{"text":"Giving them 'homework' to change their behavior.","tags":{"Organized":3,"Practical":2}},{"text":"Analyzing their childhood trauma.","tags":{"Analytical":3}},{"text":"Doing art or music therapy with them.","tags":{"Creative":3}}]},
        {"text":"How do you feel about aging and the elderly?","options":[{"text":"I love hearing their stories and holding their hands.","tags":{"Empathy":3,"Social":2}},{"text":"I am fascinated by the biology of getting older.","tags":{"Analytical":3}},{"text":"I want to build better wheelchairs and devices for them.","tags":{"Technical":3,"ProblemSolving":2}},{"text":"It depresses me to think about.","tags":{"Sensitive":3}}]}
    ],
    "Engineering": [
        {"text":"When a household appliance breaks, you:","options":[{"text":"Take it apart with a screwdriver to fix it.","tags":{"Technical":3,"Analytical":3}},{"text":"Read the manual troubleshooting guide.","tags":{"Organized":3}},{"text":"Call a repair person.","tags":{"Practical":2}},{"text":"Throw it away and buy a cooler one.","tags":{"Creative":2}}]},
        {"text":"As a kid, your favorite toy was:","options":[{"text":"Legos or building blocks.","tags":{"Technical":3,"Creative":2}},{"text":"Board games with rules.","tags":{"Logical":3}},{"text":"Action figures or dolls.","tags":{"Empathy":2}},{"text":"Art supplies and paper.","tags":{"Creative":3}}]},
        {"text":"When assembling new furniture:","options":[{"text":"Follow instructions step-by-step.","tags":{"Organized":3,"Analytical":2}},{"text":"Throw away instructions, use the picture.","tags":{"ProblemSolving":3,"Independent":2}},{"text":"Get frustrated and ask for help.","tags":{"Communication":2}},{"text":"Try to modify it to make it better.","tags":{"Creative":3}}]},
        {"text":"How do you feel about math?","options":[{"text":"Love it, there is one right answer.","tags":{"Logical":3,"Analytical":3}},{"text":"Tolerate it if it helps build something.","tags":{"Technical":3}},{"text":"Hate it, prefer debating answers.","tags":{"Communication":3}},{"text":"Struggle with numbers but get concepts.","tags":{"Creative":2}}]},
        {"text":"Seeing a long traffic jam, you think:","options":[{"text":"How to redesign roads to fix this.","tags":{"ProblemSolving":3,"Analytical":2}},{"text":"Wondering where everyone is going.","tags":{"Empathy":3}},{"text":"Look at the map for a faster detour.","tags":{"Logical":3}},{"text":"Turn up the music and relax.","tags":{"Easygoing":3}}]},
        {"text":"When completing a task, what matters most?","options":[{"text":"Efficiency—doing it the fastest/smartest way.","tags":{"Logical":3,"Technical":2}},{"text":"Quality—making it look beautiful.","tags":{"Creative":3}},{"text":"Accuracy—making zero mistakes.","tags":{"Organized":3}},{"text":"Teamwork—ensuring everyone helped.","tags":{"Leadership":3}}]},
        {"text":"Do you like getting your hands dirty?","options":[{"text":"Yes, love working with physical tools.","tags":{"Practical":3,"Technical":2}},{"text":"No, prefer a clean desk and computer.","tags":{"Analytical":3}},{"text":"Only for art or gardening.","tags":{"Creative":3}},{"text":"Don't mind it if it gets the job done.","tags":{"Adaptable":3}}]},
        {"text":"When you look at a massive bridge, you wonder:","options":[{"text":"How much weight the steel cables can hold.","tags":{"Analytical":3,"Technical":3}},{"text":"How beautiful the architecture is.","tags":{"Creative":3,"Visual":2}},{"text":"How many years it took to organize the workers.","tags":{"Organized":3,"Leadership":2}},{"text":"I just drive over it without thinking.","tags":{"Practical":2}}]},
        {"text":"What is your approach to packing the trunk of a car?","options":[{"text":"It is a game of Tetris. Every inch must be optimized.","tags":{"Analytical":3,"Spatial":3}},{"text":"I throw it all in and push the door shut.","tags":{"Easygoing":2}},{"text":"I make a list to ensure nothing is crushed.","tags":{"Organized":3}},{"text":"I ask someone else to do the heavy lifting.","tags":{"Communication":2}}]},
        {"text":"If you were dropped in the woods, you would first:","options":[{"text":"Build a structural shelter using geometry.","tags":{"Technical":3,"ProblemSolving":3}},{"text":"Observe the plants and animals to find food.","tags":{"Nature":3,"Analytical":2}},{"text":"Keep walking in a straight line to find a road.","tags":{"Logical":3}},{"text":"Panic.","tags":{"Sensitive":3}}]},
        {"text":"How do you react to a complex 3D puzzle?","options":[{"text":"I visualize the shapes rotating in my mind.","tags":{"Spatial":3,"Analytical":3}},{"text":"I force pieces together until they fit.","tags":{"Practical":2,"Dedicated":2}},{"text":"I look up the solution on YouTube.","tags":{"Resourceful":3}},{"text":"I give up, I don't have the patience.","tags":{"Easygoing":2}}]},
        {"text":"When a process at work/school is slow, you:","options":[{"text":"Design a completely new system to automate it.","tags":{"ProblemSolving":3,"Technical":3}},{"text":"Complain about it to management.","tags":{"Communication":2}},{"text":"Just do the work, even if it's slow.","tags":{"Dedicated":3}},{"text":"Find a creative shortcut to skip steps.","tags":{"Creative":2,"Logical":2}}]},
        {"text":"What sounds like the best TV show to you?","options":[{"text":"'How It's Made' (Factories and Machines).","tags":{"Technical":3,"Analytical":2}},{"text":"'Shark Tank' (Business and Pitching).","tags":{"Logical":2,"Leadership":2}},{"text":"A sci-fi movie about space travel.","tags":{"Imaginative":3}},{"text":"A reality show about fixing up houses.","tags":{"Practical":3,"Creative":2}}]},
        {"text":"You need to measure a room but have no ruler. You:","options":[{"text":"Use my shoe size to calculate the exact square footage.","tags":{"Analytical":3,"ProblemSolving":3}},{"text":"Eyeball it, I'm usually pretty close.","tags":{"Spatial":3,"Creative":2}},{"text":"Wait until I can go buy a tape measure.","tags":{"Organized":2,"Logical":2}},{"text":"Pace it out and guess.","tags":{"Practical":2}}]},
        {"text":"What is the most beautiful thing about science?","options":[{"text":"The Laws of Physics and Thermodynamics.","tags":{"Technical":3,"Analytical":3}},{"text":"The periodic table and chemical reactions.","tags":{"Logical":3}},{"text":"The way animals evolve to survive.","tags":{"Nature":3}},{"text":"The cool explosions in the lab.","tags":{"Practical":2,"Visual":2}}]},
        {"text":"When using CAD (Computer-Aided Design) software, you:","options":[{"text":"Love entering the exact millimeter dimensions.","tags":{"Organized":3,"Technical":3}},{"text":"Prefer rendering the final 3D visual with lighting.","tags":{"Creative":3,"Visual":2}},{"text":"Find it too tedious and prefer sketching on paper.","tags":{"Practical":3}},{"text":"I prefer coding the software, not using it.","tags":{"Technical":2,"Analytical":2}}]},
        {"text":"If you were building a racecar, you would focus on:","options":[{"text":"The aerodynamics and engine efficiency.","tags":{"Technical":3,"Analytical":3}},{"text":"The sleek exterior design and paint job.","tags":{"Creative":3}},{"text":"The safety cage to protect the driver.","tags":{"Empathy":2,"Logical":2}},{"text":"Getting sponsors to pay for it.","tags":{"Leadership":3}}]},
        {"text":"How do you feel about reading blueprints?","options":[{"text":"I can instantly visualize the 3D building in my head.","tags":{"Spatial":3,"Analytical":3}},{"text":"I understand the math, but it takes me a minute.","tags":{"Logical":3}},{"text":"It looks like a confusing maze of lines.","tags":{"Creative":2}},{"text":"I just want to pour the concrete.","tags":{"Practical":3}}]},
        {"text":"What is the best way to test a new invention?","options":[{"text":"Run computer simulations before building it.","tags":{"Technical":3,"Analytical":2}},{"text":"Build a physical prototype and try to break it.","tags":{"Practical":3,"ProblemSolving":3}},{"text":"Give it to a user and see if they like it.","tags":{"Empathy":3,"Social":2}},{"text":"Sell it and fix the bugs later.","tags":{"Logical":2,"Leadership":2}}]},
        {"text":"How do you handle making a mistake on a project?","options":[{"text":"I analyze the root cause so it never happens again.","tags":{"Analytical":3,"Organized":3}},{"text":"I duct-tape a quick fix so we stay on schedule.","tags":{"Practical":3,"ProblemSolving":2}},{"text":"I get very upset with myself.","tags":{"Dedicated":2}},{"text":"I try to blame the faulty materials.","tags":{"Defensive":2}}]},
        {"text":"When looking at an airplane, what amazes you?","options":[{"text":"The fluid dynamics that create lift.","tags":{"Technical":3,"Analytical":3}},{"text":"The logistics of how airports schedule flights.","tags":{"Organized":3,"Logical":2}},{"text":"The view from the window seat.","tags":{"Visual":3,"Imaginative":2}},{"text":"The fact that humans figured out how to fly at all.","tags":{"Philosophical":3}}]},
        {"text":"If you had to work with hazardous chemicals, you would:","options":[{"text":"Strictly follow every OSHA safety guideline.","tags":{"Organized":3,"Logical":3}},{"text":"Be fascinated by the extreme reactions.","tags":{"Analytical":3}},{"text":"Refuse to do it.","tags":{"Practical":2}},{"text":"Design a robot to handle them for me.","tags":{"Technical":3,"ProblemSolving":3}}]},
        {"text":"What is your philosophy on design?","options":[{"text":"Form follows function. If it doesn't work perfectly, it's garbage.","tags":{"Logical":3,"Technical":3}},{"text":"It must be beautiful, even if it's slightly less efficient.","tags":{"Creative":3}},{"text":"It must be safe and easy for a child to use.","tags":{"Empathy":3}},{"text":"It needs to be cheap to manufacture.","tags":{"Practical":3}}]},
        {"text":"How do you prefer to brainstorm solutions?","options":[{"text":"Whiteboarding diagrams, flowcharts, and equations.","tags":{"Analytical":3,"Technical":2}},{"text":"Sitting quietly alone until the 'Eureka' moment hits.","tags":{"Independent":3,"Imaginative":2}},{"text":"Arguing with a team until the best idea wins.","tags":{"Communication":3,"Logical":2}},{"text":"Building a messy model out of cardboard.","tags":{"Practical":3,"Creative":2}}]},
        {"text":"If you were to work on renewable energy, you'd choose:","options":[{"text":"Designing more efficient solar panel materials.","tags":{"Analytical":3,"Technical":3}},{"text":"Building massive offshore wind turbines.","tags":{"Practical":3,"ProblemSolving":2}},{"text":"Convincing politicians to pass green laws.","tags":{"Communication":3,"Leadership":2}},{"text":"Designing beautiful, eco-friendly smart homes.","tags":{"Creative":3,"Visual":2}}]}
    ],
    "SocialEdu": [
        {"text":"A new student joins your class. You:","options":[{"text":"Walk up, introduce myself, show them around.","tags":{"Communication":3,"Leadership":2}},{"text":"Smile, but wait for them to speak first.","tags":{"Empathy":2,"Reserved":2}},{"text":"Ignore them and focus on my work.","tags":{"Independent":3}},{"text":"Quietly observe them.","tags":{"Analytical":3}}]},
        {"text":"If you volunteered for a weekend, you would:","options":[{"text":"Tutor younger kids.","tags":{"Communication":3,"Empathy":2}},{"text":"Organize files for a charity.","tags":{"Organized":3}},{"text":"Fix up a playground.","tags":{"Technical":2,"Practical":3}},{"text":"Design flyers for an event.","tags":{"Creative":3}}]},
        {"text":"Seeing someone treated unfairly, you:","options":[{"text":"Immediately speak up and defend them.","tags":{"Leadership":3,"Empathy":3}},{"text":"Comfort the person privately afterward.","tags":{"Empathy":3,"Communication":2}},{"text":"Analyze rules to see who is technically right.","tags":{"Logical":3}},{"text":"Feel bad, but stay out of it.","tags":{"Independent":2}}]},
        {"text":"The best way to motivate people is:","options":[{"text":"Encouraging them and celebrating small wins.","tags":{"Empathy":3,"Communication":3}},{"text":"Setting clear goals and deadlines.","tags":{"Organized":3,"Leadership":2}},{"text":"Offering a reward or money.","tags":{"Logical":3}},{"text":"Letting them do things their own way.","tags":{"Creative":2}}]},
        {"text":"How patient are you?","options":[{"text":"Very. I can explain things multiple times.","tags":{"Empathy":3,"Communication":3}},{"text":"Patient with people, impatient with tech.","tags":{"Technical":2,"Empathy":2}},{"text":"Not patient. I want things done quickly.","tags":{"Logical":3,"ProblemSolving":2}},{"text":"Depends completely on my mood.","tags":{"Adaptable":2}}]},
        {"text":"If a group project fails, the reason is usually:","options":[{"text":"People aren't communicating or listening.","tags":{"Communication":3,"Empathy":2}},{"text":"The plan wasn't organized from the start.","tags":{"Organized":3}},{"text":"Not a creative enough idea.","tags":{"Creative":3}},{"text":"Someone didn't do their hard work.","tags":{"Logical":2}}]},
        {"text":"What makes a story/movie great to you?","options":[{"text":"Character development and emotional journeys.","tags":{"Empathy":3,"Communication":2}},{"text":"A complex plot with a twist ending.","tags":{"Analytical":3}},{"text":"Beautiful cinematography.","tags":{"Creative":3,"Technical":1}},{"text":"Action, explosions, and cool gadgets.","tags":{"Practical":2}}]},
        {"text":"How do you react when someone cries in front of you?","options":[{"text":"I immediately hug them and ask what's wrong.","tags":{"Empathy":3,"Emotional":3}},{"text":"I awkwardly hand them a tissue.","tags":{"Reserved":3}},{"text":"I try to offer a logical solution to their problem.","tags":{"Logical":3,"Analytical":2}},{"text":"I try to make them laugh to change the mood.","tags":{"Communication":3,"Creative":2}}]},
        {"text":"What is your teaching style?","options":[{"text":"Hands-on games and interactive group work.","tags":{"Social":3,"Creative":3}},{"text":"Clear lectures followed by a quiz.","tags":{"Organized":3,"Logical":2}},{"text":"Socratic method—asking them questions to make them think.","tags":{"Analytical":3,"Communication":2}},{"text":"I hate teaching, I just want to do the work myself.","tags":{"Independent":3}}]},
        {"text":"If you were a high school principal, your priority would be:","options":[{"text":"Ensuring every student feels safe and loved.","tags":{"Empathy":3,"Social":3}},{"text":"Raising the standardized test scores.","tags":{"Analytical":3,"Logical":2}},{"text":"Upgrading the sports and arts facilities.","tags":{"Creative":3,"Practical":2}},{"text":"Strict discipline and perfect attendance.","tags":{"Organized":3,"Leadership":3}}]},
        {"text":"When reading history, what fascinates you most?","options":[{"text":"The daily lives and struggles of normal people.","tags":{"Empathy":3,"Sociology":3}},{"text":"The military strategies and battles.","tags":{"Logical":3,"Analytical":2}},{"text":"The evolution of art, music, and culture.","tags":{"Creative":3}},{"text":"The dates, timelines, and treaties.","tags":{"Organized":3}}]},
        {"text":"How do you handle a student who won't do their homework?","options":[{"text":"Sit down with them to find out what is going on at home.","tags":{"Empathy":3,"Psychology":3}},{"text":"Give them a zero. Rules are rules.","tags":{"Logical":3,"Organized":2}},{"text":"Design a more fun, gamified assignment for them.","tags":{"Creative":3,"ProblemSolving":2}},{"text":"Send them to detention.","tags":{"Leadership":2}}]},
        {"text":"What is the most important skill for a social worker?","options":[{"text":"Boundless empathy and active listening.","tags":{"Empathy":3,"Communication":3}},{"text":"The ability to navigate complex government paperwork.","tags":{"Organized":3,"Analytical":2}},{"text":"Toughness to not let the sadness ruin your day.","tags":{"Dedicated":3,"Logical":2}},{"text":"Creative problem solving to find resources.","tags":{"ProblemSolving":3,"Resourceful":2}}]},
        {"text":"If you had a podcast, it would be about:","options":[{"text":"Interviewing everyday people about their life stories.","tags":{"Communication":3,"Empathy":3}},{"text":"Debating political and social issues.","tags":{"Logical":3,"Leadership":2}},{"text":"Explaining complex psychological theories simply.","tags":{"Analytical":3,"Edu":3}},{"text":"Reviewing the latest tech and gadgets.","tags":{"Technical":3}}]},
        {"text":"When you see a homeless person, you think:","options":[{"text":"I want to buy them a meal right now.","tags":{"Empathy":3,"Practical":2}},{"text":"We need better systemic government policies to fix this.","tags":{"Analytical":3,"Logical":3}},{"text":"I avoid making eye contact.","tags":{"Reserved":3}},{"text":"I wonder what their life story is.","tags":{"Imaginative":3,"Psychology":2}}]},
        {"text":"How do you feel about public speaking to a large crowd?","options":[{"text":"I love the energy of the audience!","tags":{"Communication":3,"Social":3}},{"text":"I prefer speaking 1-on-1 or in small groups.","tags":{"Empathy":3,"Reserved":2}},{"text":"I can do it if I read perfectly from a script.","tags":{"Organized":3}},{"text":"I would rather die.","tags":{"Reserved":3}}]},
        {"text":"What makes a community strong?","options":[{"text":"Everyone knowing each other and helping out.","tags":{"Social":3,"Empathy":3}},{"text":"A strong local economy and businesses.","tags":{"Logical":3}},{"text":"Good schools and educational programs.","tags":{"Edu":3,"Organized":2}},{"text":"Beautiful parks and public art.","tags":{"Creative":3}}]},
        {"text":"If you were a counselor, your main tool would be:","options":[{"text":"Creating a safe space for them to vent.","tags":{"Empathy":3,"Communication":3}},{"text":"Helping them map out a step-by-step recovery plan.","tags":{"Organized":3,"Logical":2}},{"text":"Analyzing their cognitive behavioral patterns.","tags":{"Analytical":3,"Psychology":3}},{"text":"Using art or play therapy to unlock emotions.","tags":{"Creative":3}}]},
        {"text":"How do you judge a person's character?","options":[{"text":"By how they treat waiters and service staff.","tags":{"Empathy":3,"Observation":3}},{"text":"By how strictly they keep their promises.","tags":{"Logical":3,"Organized":2}},{"text":"By how funny and engaging they are.","tags":{"Social":3}},{"text":"By their resume and achievements.","tags":{"Analytical":2}}]},
        {"text":"What is your philosophy on punishment?","options":[{"text":"It should be focused on rehabilitation and learning.","tags":{"Empathy":3,"Edu":3}},{"text":"It should be strict to deter future crimes.","tags":{"Logical":3,"Leadership":2}},{"text":"It should require community service to pay back society.","tags":{"Practical":3,"Social":2}},{"text":"I leave that for the judges to decide.","tags":{"Independent":2}}]},
        {"text":"When organizing a community event, you:","options":[{"text":"Rally the volunteers and get everyone hyped up.","tags":{"Leadership":3,"Communication":3}},{"text":"Manage the budget and the Excel spreadsheets.","tags":{"Organized":3,"Analytical":2}},{"text":"Design the posters and the stage layout.","tags":{"Creative":3}},{"text":"Show up on the day to help carry heavy things.","tags":{"Practical":3}}]},
        {"text":"How do you feel about kids?","options":[{"text":"I love them! I want to be around them all day.","tags":{"Empathy":3,"Social":3}},{"text":"I like them, but they tire me out quickly.","tags":{"Reserved":2}},{"text":"I prefer treating them like small adults to teach them logic.","tags":{"Analytical":3,"Edu":2}},{"text":"I find them loud and messy.","tags":{"Independent":3}}]},
        {"text":"What is the biggest problem in the world today?","options":[{"text":"A lack of basic empathy and kindness.","tags":{"Empathy":3,"Emotional":3}},{"text":"Inefficient distribution of resources and wealth.","tags":{"Analytical":3,"Logical":3}},{"text":"A lack of education and critical thinking.","tags":{"Edu":3,"Communication":2}},{"text":"Not enough sustainable technology.","tags":{"Technical":3}}]},
        {"text":"If you had to write a book, it would be:","options":[{"text":"A self-help guide to overcoming trauma.","tags":{"Empathy":3,"Psychology":3}},{"text":"A textbook on a very specific historical event.","tags":{"Analytical":3,"Organized":2}},{"text":"A children's book with beautiful illustrations.","tags":{"Creative":3,"Edu":2}},{"text":"A sci-fi novel about a dystopian government.","tags":{"Imaginative":3,"Logical":2}}]},
        {"text":"How do you celebrate someone else's success?","options":[{"text":"Throw them a huge surprise party!","tags":{"Social":3,"Communication":3}},{"text":"Write them a deeply personal, heartfelt card.","tags":{"Empathy":3,"Creative":2}},{"text":"Buy them a practical gift they can use in their career.","tags":{"Practical":3,"Logical":2}},{"text":"Give them a high-five and get back to work.","tags":{"Independent":3}}]}
    ]
};

// 2. RANDOM QUESTION SHUFFLER ROUTE
app.get('/api/questions', (req, res) => {
    const requestedInterest = req.query.interest; 
    
    // Grab the massive pool of 25 questions for that category
    const pool = questionsDB[requestedInterest] || questionsDB["TechAI"];
    
    // Shuffle the pool randomly
    const shuffledPool = [...pool].sort(() => 0.5 - Math.random());
    
    // Slice off exactly 5 questions
    const selectedQuestions = shuffledPool.slice(0, 5);
    
    res.json(selectedQuestions);
});

// =====================================================================
// 3. AI MATCHING QUEUE ENGINE & ROUTE HANDLER
// =====================================================================
const requestQueue = [];
let isProcessingQueue = false;

async function processQueue() {
    if (isProcessingQueue || requestQueue.length === 0) return;
    isProcessingQueue = true;

    // Pull the next request from the queue
    const { req, res } = requestQueue.shift();

    try {
        const { userTraits, interest, studentInput } = req.body;

        // Construct prompt dynamically inside the worker
        const prompt = `
            You are an expert career counselor for high school and college students. 
            A student is deeply interested in the broad category of: ${interest}.
            They completed a behavioral assessment and demonstrated these dominant traits: ${JSON.stringify(userTraits)}.
            They also provided this personal context about their goals/hobbies: "${studentInput}".
            
            Analyze their psychological traits alongside their personal context. Recommend 4 highly specific, modern career paths tailored exactly to them. 
            
            You MUST return the data strictly as a JSON array. Do not wrap the JSON in markdown blocks (like \`\`\`json). The JSON must perfectly match this schema:
            [
              {
                "title": "String (Name of career)",
                "icon": "Emoji",
                "desc": "String (A short encouraging summary of why it fits them)",
                "phases": [
                  { "title": "Phase 1: Foundation", "steps": "String (Specific actionable steps)" },
                  { "title": "Phase 2: Skill Building", "steps": "String" },
                  { "title": "Phase 3: Career Entry", "steps": "String" }
                ],
                "books": ["String (Book title by Author)", "String"]
              }
            ]
        `;

        // Call Gemini using the latest available Flash model
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
            config: {
                responseMimeType: "application/json",
            }
        });

        // Check if response was blocked or empty
        if (!response.text) {
            return res.status(400).json({ 
                error: "Your input triggered a safety filter. Please revise your text and try again." 
            });
        }

        // Clean out markdown wrappers if present and parse
        const cleanJsonText = response.text.replace(/```json|```/g, '').trim();
        const finalRoadmap = JSON.parse(cleanJsonText);
        
        res.json(finalRoadmap); 

    } catch (error) {
        console.error("AI Queue Error:", error);
        res.status(500).json({ 
            error: "Failed to generate roadmap. The AI encountered an unexpected issue with the input." 
        });
    } finally {
        // Cooldown ensures rate limiting and guarantees queue processing resumes even on error
        setTimeout(() => {
            isProcessingQueue = false;
            processQueue(); 
        }, 4000); 
    }
}

// Single route endpoint that queues incoming requests
app.post('/api/calculate-result', (req, res) => {
    requestQueue.push({ req, res });
    processQueue();
});

// Start the server
app.listen(PORT, () => console.log(`AI Matching Engine alive on Port ${PORT}`));